import type { CultureItem } from "@/lib/types";

export const CULTURE: CultureItem[] = [
  /* ------------------------------ CLOTHING ------------------------------ */
  {
    slug: "isicholo",
    name: "Isicholo",
    kind: "clothing",
    people: "Zulu",
    province: "KZN",
    oneLine: "The wide flared hat that announces a woman is married.",
    body: [
      "The isicholo is a broad, flared hat worn by married Zulu women. Historically it was not a hat at all but a hairstyle: a woman's own hair was grown, teased over a frame of grass and fibre, coated with red ochre and fat, and worn permanently. Removing it was a serious act.",
      "Over time it became a detachable hat, woven over a frame and often finished in red ochre or beadwork, which made it practical for modern life while keeping the signal intact.",
      "The signal is the point. The isicholo says, at a distance, that this woman is married and must be addressed accordingly. South African traditional dress is largely a language of status: married or not, in mourning or not, initiated or not, royal or commoner. You are meant to be able to read a person before they speak.",
    ],
    facts: [
      { label: "Worn by", value: "Married Zulu women" },
      { label: "Originally", value: "A permanent ochred hairstyle, later a removable hat" },
      { label: "Paired with", value: "Isidwaba (leather skirt) and beaded panels" },
      { label: "Seen at", value: "Weddings, umemulo, Reed Dance, royal occasions" },
    ],
    tags: ["Zulu", "status", "headwear"],
  },
  {
    slug: "ndebele-dress",
    name: "Ndebele beadwork and isigolwani",
    kind: "clothing",
    people: "Southern Ndebele",
    province: "MP",
    oneLine: "Beaded aprons, neck rings and the most recognisable geometry in Africa.",
    body: [
      "Ndebele women's dress is a complete visual grammar. The jocolo, a five-panelled beaded apron, is worn by married women. The ighabi and linaga blankets are layered over the shoulders. Isigolwani — thick grass hoops bound in beadwork — are worn at the neck, arms and legs, and mark stages of life.",
      "The famous geometric style on Ndebele walls and beadwork developed in the twentieth century, with the bold outlined blocks and sharp colour fields becoming a defining South African visual signature. Esther Mahlangu, who learned the form from her mother and grandmother in the traditional way, took it worldwide — painting a BMW art car in 1991 and exhibiting internationally for decades.",
      "The designs are not purely decorative. Researchers and Ndebele artists have described motifs encoding events, aspirations and in some periods coded political statements — razor blades, aeroplanes, staircases and house shapes entering the vocabulary as the world changed.",
    ],
    facts: [
      { label: "Jocolo", value: "Five-panelled beaded apron for married women" },
      { label: "Isigolwani", value: "Beaded grass hoops marking life stage" },
      { label: "Famous artist", value: "Esther Mahlangu" },
      { label: "Also found on", value: "House walls, painted by women" },
    ],
    tags: ["Ndebele", "beadwork", "art"],
  },
  {
    slug: "basotho-blanket",
    name: "Seanamarena — the Basotho blanket",
    kind: "clothing",
    people: "Basotho",
    province: "FS",
    oneLine: "A wool blanket worn like a coat, read like a CV.",
    body: [
      "The Basotho blanket is worn pinned at the shoulder and is both practical mountain clothing and a formal garment. Specific designs carry specific meanings and are given at specific moments — at initiation, at marriage, at the birth of a first child.",
      "The designs have names and are strongly associated with particular makers; Seanamarena, meaning roughly 'to swear by the chiefs', is among the best known. Motifs include maize cobs (prosperity), shields, crowns and aeroplanes.",
      "There is a convention that the stripes — the pinstripes running along the blanket — are worn vertically, and that wearing them the wrong way is a visible mistake.",
      "The blanket became formally associated with Basotho identity in the nineteenth century and has stayed central ever since. Mokorotlo, the conical straw hat shaped after a mountain, completes the outfit and appears on the Lesotho flag.",
    ],
    facts: [
      { label: "Worn", value: "Pinned at the shoulder, stripes vertical" },
      { label: "Given at", value: "Initiation, marriage, birth of a first child" },
      { label: "Motifs", value: "Maize cobs, shields, crowns, aeroplanes" },
      { label: "Paired with", value: "Mokorotlo — the conical straw hat" },
    ],
    tags: ["Basotho", "blanket", "status"],
  },
  {
    slug: "shweshwe",
    name: "Shweshwe",
    kind: "clothing",
    people: "Xhosa, Sotho, Tswana and nationwide",
    province: "EC",
    oneLine: "Indigo printed cotton, stiff as paper until you wash it.",
    body: [
      "Shweshwe is a dyed and discharge-printed cotton fabric with tiny geometric patterns, usually in indigo, chocolate brown or red. It arrived through trade and missionary routes in the nineteenth century and was absorbed so completely into South African dress that it is now unmistakably local.",
      "The name is widely linked to King Moshoeshoe I of the Basotho, who was presented with the cloth and wore it.",
      "Authentic shweshwe comes stiff, coated with a starch that has to be washed out before sewing, and it carries a backstamp. Cutting into a bolt that has not been washed is a beginner's mistake — it shrinks and softens dramatically.",
      "It is the default fabric for makoti outfits, Xhosa traditional dress, and increasingly for contemporary South African fashion design.",
    ],
    facts: [
      { label: "Colours", value: "Indigo, chocolate brown, red" },
      { label: "Name linked to", value: "King Moshoeshoe I" },
      { label: "Before sewing", value: "Wash out the starch — it shrinks" },
      { label: "Worn for", value: "Weddings, makoti dress, everyday and high fashion" },
    ],
    tags: ["fabric", "indigo", "fashion"],
  },
  {
    slug: "xibelani",
    name: "Xibelani",
    kind: "clothing",
    people: "Tsonga",
    province: "LP",
    oneLine: "A heavy layered skirt built to amplify the movement of the hips.",
    body: [
      "The xibelani is a short, thick, many-layered skirt worn by Tsonga women, and it is both the garment and the name of the dance performed in it. The skirt is deliberately bulky — it exaggerates every hip movement, so that a small motion reads as a large one from across a field.",
      "It is traditionally made from wool or strips of fabric wound and stitched into dense tiers, and it can be surprisingly heavy. Dancing in it is physically demanding.",
      "Xibelani has become one of the most visible South African dance forms online, and Tsonga artists have carried it into contemporary music video and global stages.",
    ],
    facts: [
      { label: "Worn by", value: "Tsonga women" },
      { label: "Also means", value: "The dance itself" },
      { label: "Construction", value: "Dense wound tiers of wool or fabric" },
      { label: "Effect", value: "Amplifies hip movement for visibility at distance" },
    ],
    tags: ["Tsonga", "dance", "Limpopo"],
  },
  {
    slug: "ibheshu",
    name: "Ibheshu and the amabutho look",
    kind: "clothing",
    people: "Zulu",
    province: "KZN",
    oneLine: "Cowhide apron, beaded bands, and the dress of the regiments.",
    body: [
      "Ibheshu is the cowhide apron worn by Zulu men at the back, paired with the umutsha at the front. Added to that are amashoba — cow-tail fringes worn at the arms and knees, which exaggerate the movement of a dancer — and beaded bands.",
      "Length and detail are read as status markers: younger unmarried men and senior married men wear different arrangements, and royal dress is distinct again.",
      "The full regalia appears at weddings, at Umkhosi Womhlanga, at royal occasions and in indlamu dance performance. Hide is used because cattle are the central measure of wealth and ceremony in Zulu life, so wearing cattle is a direct statement.",
    ],
    facts: [
      { label: "Ibheshu", value: "Cowhide apron worn at the back" },
      { label: "Amashoba", value: "Cow-tail fringes at arms and knees" },
      { label: "Reads as", value: "Age, marital status and rank" },
      { label: "Worn for", value: "Indlamu, weddings, royal events" },
    ],
    tags: ["Zulu", "men", "ceremony"],
  },

  /* ------------------------------ CEREMONY ------------------------------ */
  {
    slug: "umemulo",
    name: "Umemulo",
    kind: "ceremony",
    people: "Zulu",
    province: "KZN",
    oneLine: "The coming-of-age ceremony where a father publicly honours his daughter.",
    body: [
      "Umemulo marks a young Zulu woman's transition into adulthood, usually around the age of twenty-one. It is initiated by her father and it is, among other things, a public statement that she has conducted herself in a way the family is proud of.",
      "A beast is slaughtered. The young woman is secluded for a period beforehand and is then presented to the community in full beaded regalia, carrying a spear, and dances before the family and guests.",
      "A central moment is the pinning of money onto her by relatives and guests as she dances, and the giving of gifts. The ceremony also publicly signals that she may now be courted.",
      "Modern umemulo ceremonies are often large, photographed and shared widely — one of the clearest examples of a traditional rite that has adapted completely to contemporary life without losing its structure.",
    ],
    facts: [
      { label: "Age", value: "Usually around 21" },
      { label: "Initiated by", value: "The father" },
      { label: "Key symbols", value: "Spear, beadwork, slaughtered beast" },
      { label: "Signals", value: "Adulthood and readiness to be courted" },
    ],
    tags: ["Zulu", "coming of age", "women"],
  },
  {
    slug: "ulwaluko",
    name: "Ulwaluko",
    kind: "ceremony",
    people: "Xhosa and other groups",
    province: "EC",
    oneLine: "Initiation into manhood — seclusion, instruction, and a public return.",
    body: [
      "Ulwaluko is the Xhosa initiation into manhood. Initiates (abakhwetha) are secluded for a period in a purpose-built structure away from the community, undergo circumcision, and receive instruction from elders about responsibility, marriage, conduct and their obligations to the community.",
      "The return is public and transformative: the initiate is received as a man (indoda), given new clothing, and from that day is addressed and treated differently. Much of the instruction is held in confidence and is not discussed outside the practice.",
      "There is a serious contemporary problem that elders themselves raise loudly: deaths and injuries at illegal initiation schools run by unqualified people outside the traditional authority structure. Provincial governments, traditional leaders and health departments run registration and monitoring programmes, and traditional leaders have been consistently clear that these illegal schools are a corruption of the practice rather than an expression of it.",
      "Related initiation traditions exist across the country, including lebollo among Sotho and Tswana communities.",
    ],
    facts: [
      { label: "Initiates", value: "Abakhwetha" },
      { label: "Outcome", value: "Recognised as indoda — a man" },
      { label: "Confidential", value: "The teaching is not shared outside" },
      { label: "Regulated by", value: "Traditional authorities and provincial law" },
    ],
    tags: ["Xhosa", "initiation", "men"],
  },
  {
    slug: "umkhosi-womhlanga",
    name: "Umkhosi Womhlanga",
    kind: "ceremony",
    people: "Zulu",
    province: "KZN",
    oneLine: "The Reed Dance — thousands of young women carrying reeds to the king.",
    body: [
      "Umkhosi Womhlanga, the Reed Dance, is held annually in KwaZulu-Natal, usually in September, at the royal residence at eNyokeni. Young unmarried women cut reeds, carry them in procession and deliver them to the king.",
      "The ceremony is associated with the celebration of chastity and with the responsibilities and protection of young women, and it functions as a very large public gathering that reinforces the authority and continuity of the monarchy.",
      "Tens of thousands of participants attend in some years. A related ceremony, Umhlanga, is held in Eswatini.",
      "It attracts debate — about the gaze of cameras, about consent, about how a traditional institution should operate in a constitutional democracy. That debate is itself part of the living culture rather than a sign of its decline.",
    ],
    facts: [
      { label: "When", value: "Usually September" },
      { label: "Where", value: "eNyokeni Royal Palace, Nongoma" },
      { label: "Participants", value: "Young unmarried women, in very large numbers" },
      { label: "Also held in", value: "Eswatini, as Umhlanga" },
    ],
    tags: ["Zulu", "annual", "royal"],
  },
  {
    slug: "imbeleko",
    name: "Imbeleko",
    kind: "ceremony",
    people: "Xhosa, Zulu and others",
    province: "EC",
    oneLine: "Introducing a newborn to the ancestors.",
    body: [
      "Imbeleko is the ceremony that formally introduces a new child to the family's ancestors and to the community. A goat is traditionally slaughtered and the child is named and presented.",
      "The name itself comes from the word for the skin or cloth used to carry a baby on the back — the child is, in effect, being carried into the family line.",
      "Many families hold that a person who has not had imbeleko done may face difficulty later in life, and adults sometimes have the ceremony performed retrospectively.",
      "It is one of the clearest illustrations of how South African spiritual life treats the ancestors as present participants who need to be formally informed of family events — births, marriages, deaths, moves and achievements.",
    ],
    facts: [
      { label: "For", value: "A newborn child" },
      { label: "Involves", value: "Slaughter of a goat, naming, presentation" },
      { label: "Name from", value: "The cloth used to carry a baby on the back" },
      { label: "Can be done", value: "Later in life if it was missed" },
    ],
    tags: ["birth", "ancestors", "naming"],
  },
  {
    slug: "ukubuyisa",
    name: "Ukubuyisa",
    kind: "ceremony",
    people: "Nguni",
    province: "KZN",
    oneLine: "Bringing the spirit of the dead home, about a year after burial.",
    body: [
      "Ukubuyisa is performed roughly a year after a death. Its purpose is to bring the spirit of the deceased back home from the grave, so that they take their place among the family's ancestors and can be approached as one.",
      "A beast is slaughtered, the family gathers, and the deceased is formally addressed and told that they are being brought home. Beer is brewed. The ceremony is also the point at which formal mourning ends for the household.",
      "It explains something visitors often find confusing: a South African funeral is not the end of the process. There is a sequence of obligations that continues for at least a year, and failing to complete them is taken seriously.",
    ],
    facts: [
      { label: "When", value: "Around one year after the death" },
      { label: "Purpose", value: "Bring the spirit home as an ancestor" },
      { label: "Involves", value: "Slaughter, umqombothi, formal address" },
      { label: "Also marks", value: "The end of formal mourning" },
    ],
    tags: ["death", "ancestors", "mourning"],
  },
  {
    slug: "domba",
    name: "Domba",
    kind: "ceremony",
    people: "Venda",
    province: "LP",
    oneLine: "The python dance — a line of initiates moving as one body.",
    body: [
      "Domba is the final stage of the traditional Venda initiation cycle for young women. Its most recognisable element is the dance: initiates form a single chain, each holding the forearm of the person in front, and move with a stepping rhythm so that the whole line undulates like a python.",
      "The python is a significant figure in Venda cosmology, connected with water and with Lake Fundudzi.",
      "Domba is accompanied by drumming on the ngoma drum, which has its own ritual standing. The instruction given during the cycle concerns marriage, childbirth and adult responsibility.",
      "Like other initiation practices, the detailed content is held within the practice and is not published.",
    ],
    facts: [
      { label: "For", value: "Young Venda women, as the final initiation stage" },
      { label: "Form", value: "A single chained line moving as one" },
      { label: "Symbol", value: "The python" },
      { label: "Instrument", value: "The ngoma drum" },
    ],
    tags: ["Venda", "initiation", "dance"],
  },

  /* ------------------------------ MARRIAGE ------------------------------ */
  {
    slug: "lobola",
    name: "Lobola",
    kind: "marriage",
    people: "Most South African cultures",
    province: "NAT",
    oneLine: "Not buying a bride — binding two families with an obligation that can be called in.",
    body: [
      "Lobola (isiZulu and isiXhosa), magadi (Setswana), bohali (Sesotho) or bogadi is the transfer of cattle, or their cash equivalent, from the groom's family to the bride's family. It is one of the most misunderstood institutions in South African life.",
      "It is not a purchase. The function is to create a binding relationship between two families, with obligations running in both directions, and to give the bride's family standing to intervene if she is mistreated. The cattle are a public, expensive and socially witnessed commitment.",
      "The process is formal. The groom's delegation does not enter the homestead uninvited; they announce themselves, often pay a small amount for the right to speak, and then negotiate — in writing in many families, with a letter carried between the parties. Negotiations can run over months and are conducted by uncles and elders, not by the couple.",
      "Contemporary debate is live and serious: the cost, whether cash has distorted the practice, how it interacts with the Recognition of Customary Marriages Act, and whether it should change for same-sex marriages and for couples where both families are urban. Many young South Africans are negotiating their own version rather than abandoning it.",
    ],
    facts: [
      { label: "Also called", value: "Magadi, bohali, bogadi, ilobolo" },
      { label: "Paid in", value: "Cattle, or cash at an agreed per-head rate" },
      { label: "Negotiated by", value: "Uncles and elders, not the couple" },
      { label: "Legal context", value: "Recognition of Customary Marriages Act, 1998" },
    ],
    tags: ["marriage", "family", "negotiation"],
  },
  {
    slug: "umembeso",
    name: "Umembeso",
    kind: "marriage",
    people: "Zulu",
    province: "KZN",
    oneLine: "The gift ceremony where the groom's family clothes the bride's family.",
    body: [
      "Umembeso follows the lobola negotiation. The groom's family brings gifts — blankets, clothing, household goods — to the bride's family, and each gift is given to a specific named person according to their relationship to the bride.",
      "The word comes from ukwembesa, to clothe. The act is literally the clothing of the bride's family by the groom's family, and it says that the groom's people recognise and respect every individual in that household.",
      "It is a joyful, heavily photographed ceremony, with traditional dress on both sides, singing and dancing, and a strong element of good-natured competition between the two families.",
    ],
    facts: [
      { label: "Means", value: "To clothe" },
      { label: "Direction", value: "Groom's family gives to bride's family" },
      { label: "Rule", value: "Every gift is for a specific named person" },
      { label: "Comes after", value: "Lobola negotiations" },
    ],
    tags: ["Zulu", "wedding", "gifts"],
  },
  {
    slug: "umabo",
    name: "Umabo",
    kind: "marriage",
    people: "Zulu",
    province: "KZN",
    oneLine: "The traditional wedding itself — the bride gives, and the families eat together.",
    body: [
      "Umabo is the traditional Zulu wedding ceremony, often held after a white wedding, and in many families it is the one that really counts. The bride arrives at the groom's homestead with gifts she has prepared — grass mats, blankets, pillows, pots — and distributes them to his family, again by name.",
      "A central moment involves the groom's relatives being seated on grass mats brought by the bride, and the bride's family presenting the goods they have assembled over months.",
      "The ceremony formally incorporates the bride into her husband's family and its ancestors. She is received as makoti, and her conduct in the first period afterwards is watched closely by the women of that household.",
      "Reciprocity is the structure of the whole thing: lobola from his family, umembeso from his family, umabo from hers. Nobody is only giving or only receiving.",
    ],
    facts: [
      { label: "Direction", value: "Bride gives to the groom's family" },
      { label: "Key items", value: "Grass mats, blankets, pillows, cookware" },
      { label: "Outcome", value: "The bride is received as makoti" },
      { label: "Often follows", value: "A white wedding on the same weekend" },
    ],
    tags: ["Zulu", "wedding", "makoti"],
  },
  {
    slug: "go-laya",
    name: "Go laya",
    kind: "marriage",
    people: "Sotho and Tswana",
    province: "NW",
    oneLine: "The marriage advice given publicly by both families before the couple leaves.",
    body: [
      "Go laya is the formal counselling of the couple by the elders of both families. It is done in public, in front of everyone, usually near the end of the wedding, and it can be extremely direct.",
      "Aunts and uncles take turns. The advice covers conduct in the marriage, obligations to each other's families, money, children, and what to do when there is conflict — including who to go to, because the rule is that you take trouble to the family, not to strangers or to the street.",
      "What makes it powerful is that it is witnessed. The whole community hears what the couple was told, so the standard is public and the elders are accountable for the advice they gave.",
      "Equivalents exist across South African cultures — the Zulu ukuyala and the Xhosa ukuyalwa serve the same function.",
    ],
    facts: [
      { label: "Means", value: "To counsel or instruct" },
      { label: "Given by", value: "Elders from both families, in turn" },
      { label: "In front of", value: "The entire wedding" },
      { label: "Equivalents", value: "Ukuyala (Zulu), ukuyalwa (Xhosa)" },
    ],
    tags: ["marriage", "elders", "advice"],
  },
  {
    slug: "makoti",
    name: "Being makoti",
    kind: "marriage",
    people: "Nguni and Sotho-Tswana",
    province: "NAT",
    oneLine: "The new wife's apprenticeship in her husband's home — and the argument about it.",
    body: [
      "Makoti is the new bride in her husband's family. The role comes with expectations: rising early, cooking, serving elders, covering the head and shoulders, avoiding certain names, and moving carefully through a household whose rules she is still learning.",
      "Supporters describe it as an apprenticeship in a new family and a period of earning trust. Critics describe it as unpaid labour with a gendered double standard, since there is no equivalent probation for the husband in his wife's family.",
      "Both of those are argued fiercely in South African homes, group chats and talk radio every week. Many couples now negotiate explicitly about what they will and will not keep.",
      "Hlonipha — the respect practice of avoiding certain words and the names of in-laws — is connected to this role, and historically produced a whole parallel vocabulary used by married women.",
    ],
    facts: [
      { label: "Means", value: "New bride / daughter-in-law" },
      { label: "Associated with", value: "Hlonipha — avoidance and respect speech" },
      { label: "Debated over", value: "Gendered labour and double standards" },
      { label: "Changing", value: "Many couples now negotiate the terms openly" },
    ],
    tags: ["marriage", "gender", "debate"],
  },

  /* -------------------------------- MUSIC ------------------------------- */
  {
    slug: "maskandi",
    name: "Maskandi",
    kind: "music",
    people: "Zulu",
    province: "KZN",
    oneLine: "Zulu guitar music with izibongo in the middle of the song.",
    body: [
      "Maskandi is Zulu folk guitar music, built around a picked guitar style, concertina, and a vocal delivery that moves between singing and spoken praise poetry. Almost every maskandi song contains a section where the musician recites their own izibongo at speed — naming themselves, their clan and their home.",
      "It grew with migrant labour. Men travelling between rural KwaZulu-Natal and the cities carried guitars and wrote about the journey, the work, the distance from home and the people they left.",
      "The music opens with izihlabo, a rapid unaccompanied flourish on the guitar that establishes the player's skill before the song proper starts.",
      "Phuzekhemisi, Mfaz' Omnyama, Ihhashi Elimhlophe and Shwi noMtekhala are among the names that carried it; it remains commercially huge in KwaZulu-Natal and has fed into amapiano and gqom crossovers.",
    ],
    facts: [
      { label: "Instruments", value: "Guitar, concertina, bass, drums" },
      { label: "Izihlabo", value: "The unaccompanied opening flourish" },
      { label: "Contains", value: "Spoken izibongo mid-song" },
      { label: "Roots in", value: "Migrant labour travel" },
    ],
    tags: ["Zulu", "guitar", "izibongo"],
  },
  {
    slug: "isicathamiya",
    name: "Isicathamiya",
    kind: "music",
    people: "Zulu",
    province: "KZN",
    oneLine: "A cappella harmony sung softly, with footwork designed not to wake the hostel.",
    body: [
      "Isicathamiya is unaccompanied male choral music from Zulu migrant workers in the hostels of Durban and Johannesburg. The name comes from ukucathama — to walk softly, to stalk — and refers both to the restrained singing and to the light, controlled footwork of the performers.",
      "The story usually told is that the style became quiet because singers rehearsing in hostels at night had to avoid being heard by the guards.",
      "Competitions ran all night on Saturdays, with choirs judged on harmony, uniform, discipline and choreography. These competitions still happen.",
      "Ladysmith Black Mambazo, formed by Joseph Shabalala, took the form worldwide, particularly after Paul Simon's Graceland in 1986, and won multiple Grammy awards.",
    ],
    facts: [
      { label: "Means", value: "To stalk / tread softly" },
      { label: "Form", value: "Unaccompanied male choir" },
      { label: "Born in", value: "Migrant worker hostels" },
      { label: "Best known group", value: "Ladysmith Black Mambazo" },
    ],
    tags: ["Zulu", "a cappella", "hostels"],
  },
  {
    slug: "kwaito",
    name: "Kwaito",
    kind: "music",
    people: "Township South Africa",
    province: "GP",
    oneLine: "The sound of the first free generation — house music slowed down and spoken over.",
    body: [
      "Kwaito emerged in Johannesburg townships in the early 1990s: house music slowed to a lower bpm, with vocals chanted or spoken in Iscamtho, isiZulu, Sesotho and English rather than sung.",
      "It arrived with democracy and became the soundtrack of the generation that came of age in 1994. Its subject matter was deliberately local — the street, the party, the shebeen, money, politics — and the language was the township's own.",
      "Arthur Mafokate, Boom Shaka, Trompies, TKZee, Mandoza, Zola and Mdu Masilela defined the era. Mandoza's Nkalakatha in 2000 crossed into every demographic in the country in a way almost no song had before.",
      "Kwaito is the direct ancestor of South Africa's current global exports. Gqom came out of Durban in the 2010s, and amapiano — with its log drum and jazz-inflected keys — went from Gauteng to worldwide dominance in the 2020s.",
    ],
    facts: [
      { label: "Emerged", value: "Early 1990s, Johannesburg" },
      { label: "Built from", value: "House music, slowed down" },
      { label: "Language", value: "Iscamtho and township multilingualism" },
      { label: "Descendants", value: "Gqom, amapiano" },
    ],
    tags: ["kwaito", "township", "1990s"],
  },
  {
    slug: "amapiano",
    name: "Amapiano",
    kind: "music",
    people: "Gauteng, now global",
    province: "GP",
    oneLine: "Log drum, jazzy keys, shakers — the biggest thing South Africa has exported this century.",
    body: [
      "Amapiano — 'the pianos' — grew in Gauteng townships in the mid-2010s out of kwaito, deep house and lounge music. Its signature is the log drum: a deep, bending, percussive bassline that functions as both rhythm and hook.",
      "The sound is built around spacious jazzy keys, shakers, long builds and extended drops, and tracks are often seven or eight minutes long because they are designed for a room rather than a radio edit.",
      "It spread first through WhatsApp groups and free file-sharing rather than through labels, which is a big part of why it moved so fast.",
      "Kabza De Small, DJ Maphorisa, Focalistic, Uncle Waffles, Tyler ICU, Musa Keys and many others carried it to Lagos, London and beyond. It is currently the most internationally visible South African cultural product.",
    ],
    facts: [
      { label: "Means", value: "The pianos" },
      { label: "Signature", value: "The log drum bassline" },
      { label: "Emerged", value: "Mid-2010s, Gauteng" },
      { label: "Spread via", value: "WhatsApp and free file-sharing" },
    ],
    tags: ["amapiano", "contemporary", "global"],
  },
  {
    slug: "mbaqanga",
    name: "Mbaqanga and marabi",
    kind: "music",
    people: "Urban South Africa",
    province: "GP",
    oneLine: "The shebeen piano of the 1920s and the groaning bass voice of the 1960s.",
    body: [
      "Marabi came first — a repetitive, rolling keyboard style played in shebeens in Johannesburg's slumyards from the 1920s, built on a short cycling chord pattern that could run all night.",
      "Marabi fed into African jazz and then into mbaqanga in the 1960s: an electric, driving dance music with a distinctive deep male 'groaner' vocal underneath female harmony lines.",
      "Mahlathini and the Mahotella Queens are the canonical example — Simon 'Mahlathini' Nkabinde's bass growl with the Queens' soaring harmony above it.",
      "The word mbaqanga means a steamed maize bread — musicians used it to mean the everyday dish that keeps you alive, which is to say, the music that paid the rent.",
    ],
    facts: [
      { label: "Marabi", value: "1920s shebeen keyboard music" },
      { label: "Mbaqanga", value: "1960s electric township dance music" },
      { label: "Groaner", value: "The deep male vocal style" },
      { label: "Name means", value: "A steamed maize bread — everyday food" },
    ],
    tags: ["jazz", "mbaqanga", "history"],
  },
  {
    slug: "ghoema",
    name: "Ghoema and the Cape",
    kind: "music",
    people: "Cape coloured and Cape Malay communities",
    province: "WC",
    oneLine: "A drum, a beat, and a carnival that has run since emancipation.",
    body: [
      "Ghoema is both a small barrel drum and the distinctive syncopated beat associated with Cape Town's coloured and Cape Malay musical traditions. Its roots lie with enslaved people brought to the Cape from Southeast Asia, India, Madagascar and East Africa.",
      "The beat drives the Kaapse Klopse, the Cape Town Minstrel Carnival, held on 2 January each year — Tweede Nuwe Jaar. The date traces to the day enslaved people were historically given off, and the carnival has been running in some form since the 1800s.",
      "Associated forms include the Malay Choirs with their nederlandslied and the moppies, comic songs performed at speed.",
      "Ghoema rhythm has fed directly into contemporary South African pop, jazz and the work of composers who have built whole orchestral works around it.",
    ],
    facts: [
      { label: "Ghoema", value: "Both a drum and a rhythm" },
      { label: "Carnival", value: "Kaapse Klopse, 2 January" },
      { label: "Tweede Nuwe Jaar", value: "Historically the day off for enslaved people" },
      { label: "Related", value: "Malay Choirs, moppies, nederlandslied" },
    ],
    tags: ["Cape Town", "carnival", "drum"],
  },

  /* -------------------------------- DANCE ------------------------------- */
  {
    slug: "indlamu",
    name: "Indlamu",
    kind: "dance",
    people: "Zulu",
    province: "KZN",
    oneLine: "Lift the leg above the head, bring it down flat, and shake the ground.",
    body: [
      "Indlamu is the high-kicking Zulu dance in which the dancer raises one leg to full height and brings the foot down flat and hard on the ground, in unison with drums. It descends from warrior dance traditions and is performed in full regalia with shield and stick.",
      "It is deliberately heavy. The impact of the foot is the point, and the amashoba cow-tail fringes at the knees and arms exaggerate every movement.",
      "It is performed at weddings, ceremonies and competitions, and is the dance most often seen internationally as shorthand for South African traditional dance.",
      "The discipline required is severe — the dancer must land flat, in time, without breaking the line of the body, and amateurs give themselves away immediately by landing on the heel.",
    ],
    facts: [
      { label: "Movement", value: "Full-height kick, flat landing" },
      { label: "Worn", value: "Ibheshu, amashoba, shield and stick" },
      { label: "Accompanied by", value: "Drums and chanting" },
      { label: "Performed at", value: "Weddings, ceremonies, competitions" },
    ],
    tags: ["Zulu", "dance", "drums"],
  },
  {
    slug: "gumboot",
    name: "Gumboot dance",
    kind: "dance",
    people: "Mineworkers",
    province: "GP",
    oneLine: "Communication invented in the dark by men who were forbidden to talk.",
    body: [
      "Isicathulo, the gumboot dance, was created by Black mineworkers on the Witwatersrand. Working in flooded underground shafts, they were issued rubber gumboots, and in many accounts they were forbidden from talking while working.",
      "The dancers slap the boots, stamp, and clap in complex rhythmic patterns. The widely told account is that these patterns began as a code — a way to communicate across the dark and the noise where speech was not allowed.",
      "It moved from the shafts to hostel entertainment to competition, and then onto stages worldwide.",
      "It is one of the clearest cases in South African culture of an art form created directly out of an oppressive system and then taken over by the people who were subjected to it.",
    ],
    facts: [
      { label: "Also called", value: "Isicathulo" },
      { label: "Origin", value: "Witwatersrand gold mines" },
      { label: "Instruments", value: "The boots themselves, plus clapping" },
      { label: "Function", value: "Rhythmic communication, then performance" },
    ],
    tags: ["mines", "dance", "resistance"],
  },
  {
    slug: "pantsula",
    name: "Pantsula",
    kind: "dance",
    people: "Township South Africa",
    province: "GP",
    oneLine: "Fast footwork, Dickies and Converse — a whole subculture, not just a dance.",
    body: [
      "Pantsula is a township street dance built on extremely fast, low, intricate footwork, performed in crews and tightly synchronised. It emerged in the townships from around the 1950s and 60s and developed alongside kwaito.",
      "It is a complete subculture with its own dress code — Dickies trousers, Converse All Stars, bucket hats, Spitz shoes — its own slang and its own stance.",
      "Under apartheid, pantsula crews used performance as a way of occupying public space and commenting on political life, and the dance carried protest content that could not be stated directly.",
      "Today crews compete, teach, and perform internationally, and pantsula shows up constantly in South African music video and advertising.",
    ],
    facts: [
      { label: "Core", value: "Fast, low, precise footwork" },
      { label: "Dress", value: "Dickies, Converse, bucket hat" },
      { label: "Emerged", value: "1950s–60s townships" },
      { label: "Form", value: "Crew-based and competitive" },
    ],
    tags: ["township", "street dance", "subculture"],
  },
  {
    slug: "riel",
    name: "Riel dance",
    kind: "dance",
    people: "Khoe, San and Nama descendant communities",
    province: "NC",
    oneLine: "Dust, stamping and courtship — one of the oldest dance forms in the country.",
    body: [
      "The riel is a fast stamping dance from the Northern Cape and the Karoo, performed by communities descended from Khoe, San and Nama people, and widely regarded as among the oldest surviving dance traditions in South Africa.",
      "It is danced on bare earth and the dust it raises is part of the performance. Movements imitate animal behaviour and courtship, and dancers wear veldskoene, hats and working clothes rather than costume.",
      "It almost disappeared. A concerted revival from around 2006, including the ATKV Riel Dance competition, brought it back into schools and communities across the Northern Cape, and there are now competitive teams of children and adults.",
      "It is one of the clearest examples of a tradition that was nearly lost and was deliberately brought back.",
    ],
    facts: [
      { label: "Region", value: "Northern Cape and Karoo" },
      { label: "Danced on", value: "Bare earth — the dust is part of it" },
      { label: "Themes", value: "Animal movement and courtship" },
      { label: "Revived", value: "From around 2006 through competitions" },
    ],
    tags: ["Khoe", "San", "Northern Cape", "revival"],
  },

  /* -------------------------------- CRAFT ------------------------------- */
  {
    slug: "zulu-beadwork",
    name: "Ucu — the Zulu love letter",
    kind: "craft",
    people: "Zulu",
    province: "KZN",
    oneLine: "Beads arranged into a message you can wear around your neck.",
    body: [
      "Zulu beadwork carries meaning through colour and geometry. The ucu — often called the Zulu love letter — is a small beaded panel made by a young woman and given to a young man, carrying a message he is expected to be able to read.",
      "Colour has conventional associations that are widely described: white for purity and true love, black for difficulty or marriage, red for strong feeling or heartache, green for longing or contentment, blue for faithfulness or distance, yellow for wealth, pink for poverty or a promise.",
      "Meaning is not fixed in a dictionary sense. It depends on combination, on the pattern, on the region, and on what the two people already know. Beadwork is read in context, which is precisely what makes it a private language.",
      "The triangle is a core unit: its orientation is widely read as indicating gender and marital status, and two triangles joined in different ways produce further meanings.",
    ],
    facts: [
      { label: "Ucu", value: "A beaded love letter" },
      { label: "Read through", value: "Colour, pattern and context" },
      { label: "Core shape", value: "The triangle" },
      { label: "Made by", value: "Young women, historically" },
    ],
    tags: ["Zulu", "beadwork", "language"],
  },
  {
    slug: "ndebele-wall-painting",
    name: "Ndebele wall painting",
    kind: "craft",
    people: "Southern Ndebele",
    province: "MP",
    oneLine: "Women repaint the house, and the house announces what happened to the family.",
    body: [
      "Ndebele homesteads are painted by the women of the household in bold geometric designs with heavy black outlines. The practice is passed from mother to daughter and is done freehand, without stencils or rulers — the precision is entirely in the hand.",
      "Repainting marks events: a marriage, an initiation, a return, a death. A freshly painted homestead is a public statement that something has changed inside it.",
      "Earlier work used earth pigments, cow dung and lime in ochres and whites. Commercial acrylics arrived in the twentieth century and produced the saturated blues, greens, reds and yellows now associated with the style.",
      "Esther Mahlangu is the best known practitioner internationally — she painted a BMW 525i art car in 1991 and has exhibited and painted around the world for decades, while continuing to teach the technique to young women.",
    ],
    facts: [
      { label: "Painted by", value: "Women, freehand" },
      { label: "Marks", value: "Marriages, initiations, returns, deaths" },
      { label: "Earlier pigments", value: "Earth, lime and cow dung" },
      { label: "Carried worldwide by", value: "Esther Mahlangu" },
    ],
    tags: ["Ndebele", "painting", "women", "architecture"],
  },
  {
    slug: "basket-weaving",
    name: "Zulu and Tsonga basketry",
    kind: "craft",
    people: "Zulu, Tsonga and others",
    province: "KZN",
    oneLine: "Coiled grass so tight the basket holds beer without leaking.",
    body: [
      "Traditional Zulu ukhamba and imbenge basketry is coiled from ilala palm and grass so tightly that the vessel swells when wet and becomes watertight — tight enough to hold umqombothi.",
      "Different forms have different jobs: imbenge are small lids used to cover beer pots, iqhaga are large storage vessels, and the shapes are standardised by function rather than by decoration.",
      "Natural dyes from bark, roots and mud produce the browns, blacks and ochres; patterns are built into the coil as the weaver works, meaning the design must be planned before it is begun.",
      "Hlabisa in KwaZulu-Natal is particularly associated with the craft, and master weavers are recognised by name in the collecting world.",
    ],
    facts: [
      { label: "Material", value: "Ilala palm and grass" },
      { label: "Watertight", value: "The coil swells when wet" },
      { label: "Ukhamba", value: "Beer pot" },
      { label: "Imbenge", value: "Small lid or shallow basket" },
    ],
    tags: ["weaving", "Zulu", "craft"],
  },
  {
    slug: "wire-art",
    name: "Wire and tin art",
    kind: "craft",
    people: "Urban and rural South Africa",
    province: "NAT",
    oneLine: "Toys built from fence wire and cooldrink cans, now in galleries.",
    body: [
      "Children across southern Africa build wire cars — often elaborate, with working steering on a long rod, doors that open and tyres cut from old flip-flops. The skill is self-taught and transmitted peer to peer.",
      "The same tradition produced the wire-and-bead craft industry: animals, bowls, chandeliers and sculptures made from galvanised wire and glass beads, sold at roadsides and exported.",
      "Tin from cooldrink cans is cut and folded into windmills, aeroplanes and models. The Zulu term for this kind of improvisation sits close to the national habit of making a plan.",
      "It sits in an interesting place between children's play, informal livelihood and recognised contemporary craft — the same object can be a toy, an income and a gallery piece.",
    ],
    facts: [
      { label: "Materials", value: "Fence wire, tin cans, beads, old rubber" },
      { label: "Classic object", value: "A wire car with long-rod steering" },
      { label: "Learned", value: "Peer to peer, not formally taught" },
      { label: "Now also", value: "An export craft industry" },
    ],
    tags: ["recycling", "toys", "craft"],
  },

  /* -------------------------------- HOMES ------------------------------- */
  {
    slug: "indlu-yesizulu",
    name: "Indlu yesiZulu — the beehive house",
    kind: "home",
    people: "Zulu",
    province: "KZN",
    oneLine: "A dome of bent saplings and thatch, built without a single nail.",
    body: [
      "The iQukwane or indlu yesiZulu is a hemispherical dome built from a frame of bent saplings lashed together and covered in tightly bound thatch. No nails, no cut timber frame, no imported material.",
      "The dome is structurally excellent — it sheds wind and rain, and the thatch insulates against both summer heat and winter cold far better than corrugated iron.",
      "Interior space is organised rather than open. The umsamo at the back is the area associated with the ancestors; there are conventions about where men and women sit, where visitors are received, and where the hearth goes. Entering and seating yourself incorrectly is a visible error.",
      "The homestead, the umuzi, is itself arranged according to rules, built around a central cattle enclosure with houses positioned by seniority.",
    ],
    facts: [
      { label: "Structure", value: "Bent sapling dome, lashed and thatched" },
      { label: "Umsamo", value: "The ancestral area at the rear" },
      { label: "Umuzi", value: "The homestead, arranged around the cattle kraal" },
      { label: "Performance", value: "Cooler in summer and warmer in winter than iron" },
    ],
    tags: ["architecture", "Zulu", "thatch"],
  },
  {
    slug: "rondavel",
    name: "The rondavel",
    kind: "home",
    people: "Across southern Africa",
    province: "NAT",
    oneLine: "Round walls, conical thatch, and better climate performance than most new builds.",
    body: [
      "The rondavel is a round single-room house with a conical thatched roof, found across southern Africa in many local variants. Walls may be of mud and stone, wattle and daub, or brick.",
      "The round form resists wind from any direction, uses less wall material per unit of floor area than a rectangle, and the thick walls and deep thatch produce a genuinely stable internal temperature without any mechanical cooling.",
      "A homestead typically consists of several rondavels serving different functions — sleeping, cooking, receiving guests — rather than one subdivided house. The relationships between the structures encode family structure.",
      "Thatching is a skilled trade with its own tools and standards, and a well-laid thatch roof is expected to last decades.",
    ],
    facts: [
      { label: "Shape", value: "Circular plan, conical roof" },
      { label: "Advantage", value: "Wind-resistant and thermally stable" },
      { label: "Homestead", value: "Several single-function huts, not one divided house" },
      { label: "Roof life", value: "Decades, if correctly thatched" },
    ],
    tags: ["architecture", "thatch", "climate"],
  },
  {
    slug: "ndebele-homestead",
    name: "The painted Ndebele homestead",
    kind: "home",
    people: "Southern Ndebele",
    province: "MP",
    oneLine: "A courtyard wall that functions as a public noticeboard.",
    body: [
      "The Ndebele homestead is organised around an enclosed front courtyard, with the entrance wall and the courtyard walls carrying the painted designs the culture is known for.",
      "The painted facade is deliberately outward-facing. It is meant to be seen from the road, and it communicates the standing, the events and the aspirations of the household to everyone who passes.",
      "Low walls, built-in seating and stepped platforms shape the courtyard into a receiving space. There is a clear gradient from public to private as you move inward, and visitors are managed by the architecture itself.",
      "The painting is renewed regularly, which means the building is never finished — it is an ongoing surface that gets rewritten as the family's life changes.",
    ],
    facts: [
      { label: "Organised around", value: "An enclosed front courtyard" },
      { label: "Facade", value: "Outward-facing, meant to be read from the road" },
      { label: "Gradient", value: "Public to private as you move inward" },
      { label: "Surface", value: "Repainted as the family's circumstances change" },
    ],
    tags: ["Ndebele", "architecture", "painting"],
  },
];

export const CULTURE_BY_SLUG = Object.fromEntries(CULTURE.map((c) => [c.slug, c]));

export const CULTURE_KINDS: { id: CultureItem["kind"]; label: string; emoji: string }[] = [
  { id: "clothing", label: "Clothing", emoji: "👗" },
  { id: "ceremony", label: "Ceremonies", emoji: "🪘" },
  { id: "marriage", label: "Marriage", emoji: "💍" },
  { id: "music", label: "Music", emoji: "🥁" },
  { id: "dance", label: "Dance", emoji: "💃🏾" },
  { id: "craft", label: "Crafts", emoji: "🧵" },
  { id: "home", label: "Traditional homes", emoji: "🏠" },
];
