import type { Post } from "@/lib/types";

/**
 * Seeded feed posts. Every one is flagged `seeded: true` and is labelled in the UI as a
 * sample entry — the feed fills with real community uploads as soon as people contribute.
 */
export const POSTS: Post[] = [
  {
    id: "p-diketo-gogo",
    handle: "@gogo.nomusa",
    name: "Gogo Nomusa",
    avatarSeed: "nomusa",
    place: "Nquthu",
    province: "KZN",
    caption: "This is how my grandmother taught me Diketo. Ten stones. Nobody counts for you.",
    body: "She made me play with my left hand too, so that I would not be useless if I hurt the right one. I am 78 and I can still clear seven rounds.",
    kind: "game",
    mediaKind: "video",
    duration: "1:42",
    likes: 12840,
    comments: [
      { who: "@thabang_m", text: "My gogo did the EXACT same left hand thing 😭" },
      { who: "@lerato.k", text: "I thought my family invented this rule" },
      { who: "@sine", text: "Seven rounds at 78. Respect." },
    ],
    tags: ["diketo", "games", "KZN"],
    link: { section: "games", slug: "diketo", label: "Learn Diketo" },
    elder: true,
    seeded: true,
  },
  {
    id: "p-umngqusho",
    handle: "@mama.zodwa",
    name: "Zodwa M.",
    avatarSeed: "zodwa",
    place: "Mthatha",
    province: "EC",
    caption: "Our family's umngqusho. The marrow bone goes in at the start — that is the whole secret.",
    body: "My mother-in-law did not tell me this for six years. Six years of flat umngqusho. Then one Christmas she just said it like it was nothing.",
    kind: "food",
    mediaKind: "video",
    duration: "3:08",
    likes: 24100,
    comments: [
      { who: "@kgaugelo", text: "SIX YEARS 😂😂" },
      { who: "@bongz", text: "Making this Sunday. Will report back." },
      { who: "@aunty_pat", text: "Also add a little sugar bean water back at the end. Trust me." },
    ],
    tags: ["umngqusho", "recipe", "EC"],
    link: { section: "food", slug: "umngqusho", label: "Get the recipe" },
    seeded: true,
  },
  {
    id: "p-izibongo-mkhulu",
    handle: "@imbongi.sipho",
    name: "Sipho Ndlovu",
    avatarSeed: "sipho",
    place: "Nongoma",
    province: "KZN",
    caption: "Izibongo for my grandfather. He was a miner for 31 years. He never once called it hard.",
    body: "I wrote this the week he died. I performed it at the funeral and my aunts told me I did it too fast. I did it at the right speed.",
    kind: "poetry",
    mediaKind: "audio",
    duration: "1:14",
    likes: 31200,
    comments: [
      { who: "@nolwazi", text: "The line about the lamp. I had to sit down." },
      { who: "@mo_dintwe", text: "Your aunts were wrong. That IS the speed." },
      { who: "@thandi.x", text: "Now I want to write one for my ouma" },
    ],
    tags: ["izibongo", "poetry", "mines"],
    mediaUrl: "/audio/izibongo-explainer.mp3",
    link: { section: "poetry", slug: "praise-your-gogo", label: "Try the challenge" },
    seeded: true,
  },
  {
    id: "p-morabaraba",
    handle: "@ntate.molefe",
    name: "Ntate Molefe",
    avatarSeed: "molefe",
    place: "Ficksburg",
    province: "FS",
    caption: "You young people play chess. Sit down. I will show you the double mill.",
    body: "We drew these boards in the dust while the cattle grazed. I have beaten four generations of this family on a board scratched with a stick.",
    kind: "game",
    mediaKind: "video",
    duration: "4:30",
    likes: 18700,
    comments: [
      { who: "@chess_bra", text: "Lost in 11 moves. I am humbled." },
      { who: "@kabelo", text: "My grandfather called this umlabalaba" },
      { who: "@zinhle_", text: "The pivot cow trick is EVIL" },
    ],
    tags: ["morabaraba", "strategy", "FS"],
    link: { section: "games", slug: "morabaraba", label: "Play Morabaraba" },
    elder: true,
    seeded: true,
  },
  {
    id: "p-wedding-soweto",
    handle: "@rorisang",
    name: "Rorisang D.",
    avatarSeed: "rorisang",
    place: "Soweto",
    province: "GP",
    caption: "This is how weddings were done in my family. My grandmother lists every gift by name.",
    body: "Umabo. She says if you cannot name every person in that family, you are not married into it yet, you are just visiting.",
    kind: "culture",
    mediaKind: "video",
    duration: "5:12",
    likes: 44300,
    comments: [
      { who: "@makoti_diaries", text: "'You are just visiting' 💀 she did not have to go that hard" },
      { who: "@lesedi", text: "My umabo is in November. Saving this." },
      { who: "@gogo.mavis", text: "She is correct. Learn the names." },
    ],
    tags: ["umabo", "marriage", "Soweto"],
    link: { section: "culture", slug: "umabo", label: "About umabo" },
    seeded: true,
  },
  {
    id: "p-kgati",
    handle: "@orlando.girls",
    name: "Orlando West Crew",
    avatarSeed: "orlando",
    place: "Soweto",
    province: "GP",
    caption: "Kgati at double tempo. The song decides how long you survive.",
    kind: "game",
    mediaKind: "video",
    duration: "0:58",
    likes: 67500,
    comments: [
      { who: "@zee", text: "The girl in blue is a machine" },
      { who: "@mpho.t", text: "We sing a different verse in Mamelodi, posting ours" },
      { who: "@carla", text: "Teaching this at my school on Monday" },
    ],
    tags: ["kgati", "games", "rope"],
    link: { section: "games", slug: "kgati", label: "Learn Kgati" },
    seeded: true,
  },
  {
    id: "p-venda-lake",
    handle: "@vho.masindi",
    name: "Vho-Masindi",
    avatarSeed: "masindi",
    place: "Near Fundudzi",
    province: "LP",
    caption: "Before you come to the lake, learn the greeting. You do not face it directly.",
    body: "People arrive with cameras and no permission. I am recording this so that at least you cannot say nobody told you.",
    kind: "place",
    mediaKind: "audio",
    duration: "0:50",
    likes: 29800,
    comments: [
      { who: "@hikers_sa", text: "Thank you for this. Cancelling our trip until we go through the custodians." },
      { who: "@ndivho", text: "My family is from there. Thank you Vho-Masindi." },
    ],
    tags: ["Fundudzi", "sacred", "Venda"],
    mediaUrl: "/audio/fundudzi-1.mp3",
    link: { section: "map", slug: "fundudzi", label: "See it on the map" },
    elder: true,
    seeded: true,
  },
  {
    id: "p-isizulu-clicks",
    handle: "@learn.with.ayanda",
    name: "Ayanda",
    avatarSeed: "ayanda",
    place: "Durban",
    province: "KZN",
    caption: "C, Q, X. Three clicks, sixty seconds. Stop saying you cannot do it.",
    body: "C is the tsk of disapproval. Q is a cork popping. X is the sound you make at a horse. You already know all three.",
    kind: "language",
    mediaKind: "video",
    duration: "1:04",
    likes: 89400,
    comments: [
      { who: "@mark_v", text: "40 years in this country. Finally got Q." },
      { who: "@nandi", text: "Teaching my coworkers tomorrow" },
      { who: "@sizwe.m", text: "Now do the Xhosa fifteen 😭" },
    ],
    tags: ["isiZulu", "clicks", "pronunciation"],
    link: { section: "languages", slug: "zul", label: "Learn isiZulu" },
    seeded: true,
  },
  {
    id: "p-sophiatown",
    handle: "@ntate.sechaba",
    name: "Ntate Sechaba",
    avatarSeed: "sechaba",
    place: "Sophiatown",
    province: "GP",
    caption: "I was a boy here in 1955. They knocked it down and called the new suburb Triomf.",
    body: "Triumph. They actually named it that. I walk this street and I can still tell you which house was which.",
    kind: "story",
    mediaKind: "audio",
    duration: "0:50",
    likes: 52600,
    comments: [
      { who: "@history_teacher_za", text: "Playing this for my Grade 11s on Monday." },
      { who: "@lwazi", text: "My great-grandmother was moved to Meadowlands. Nobody in my family talks about it." },
      { who: "@jules", text: "Please record more Ntate. Please." },
    ],
    tags: ["Sophiatown", "1955", "removals"],
    mediaUrl: "/audio/sophiatown-1.mp3",
    link: { section: "stories", slug: "sophiatown-before-the-trucks", label: "Listen to the full story" },
    elder: true,
    seeded: true,
  },
  {
    id: "p-chakalaka",
    handle: "@bra.tebza",
    name: "Tebza",
    avatarSeed: "tebza",
    place: "Tembisa",
    province: "GP",
    caption: "Chakalaka but you fry the curry powder FIRST. Everyone skips this step.",
    kind: "food",
    mediaKind: "video",
    duration: "1:31",
    likes: 71200,
    comments: [
      { who: "@nthabi", text: "Thirty seconds in the oil. Game changer." },
      { who: "@braai_master", text: "Also it's better on day two, fight me" },
      { who: "@ruth.p", text: "My mother has been doing it wrong since 1987" },
    ],
    tags: ["chakalaka", "braai", "recipe"],
    link: { section: "food", slug: "chakalaka", label: "Get the recipe" },
    seeded: true,
  },
  {
    id: "p-ndebele-paint",
    handle: "@sibongile.paints",
    name: "Sibongile",
    avatarSeed: "sibongile",
    place: "Mpumalanga",
    province: "MP",
    caption: "No ruler. No stencil. My grandmother's hand, then my mother's, now mine.",
    body: "People ask what we measure with. Nothing. You learn the proportion by painting it two hundred times.",
    kind: "culture",
    mediaKind: "video",
    duration: "2:02",
    likes: 103000,
    comments: [
      { who: "@design_sa", text: "The line weight is insane. Freehand." },
      { who: "@esther_fan", text: "Esther Mahlangu energy ❤️" },
      { who: "@jo", text: "I need this on my wall" },
    ],
    tags: ["Ndebele", "art", "painting"],
    link: { section: "culture", slug: "ndebele-wall-painting", label: "About Ndebele painting" },
    seeded: true,
  },
  {
    id: "p-water-path",
    handle: "@mama.nosipho",
    name: "Mama Nosipho",
    avatarSeed: "nosipho",
    place: "Near Mthatha",
    province: "EC",
    caption: "Two trips to the river before school. We complained every day. It was also the best part of the day.",
    kind: "story",
    mediaKind: "audio",
    duration: "0:47",
    likes: 38900,
    comments: [
      { who: "@aphiwe", text: "The part about the path being the only free time. Oof." },
      { who: "@teacher_jo", text: "'You could tell which girls fetched water by how they stood'" },
    ],
    tags: ["childhood", "water", "EC"],
    mediaUrl: "/audio/water-1.mp3",
    link: { section: "stories", slug: "water-before-school", label: "Listen to the full story" },
    elder: true,
    seeded: true,
  },
  {
    id: "p-masonja",
    handle: "@limpopo.kitchen",
    name: "Khensani",
    avatarSeed: "khensani",
    place: "Giyani",
    province: "LP",
    caption: "Masonja fried crisp with chilli. Stop pulling that face, you eat prawns.",
    kind: "food",
    mediaKind: "video",
    duration: "1:18",
    likes: 95600,
    comments: [
      { who: "@dan_ct", text: "Fair point about the prawns tbh" },
      { who: "@rhulani", text: "My aunt sells these by the bucket in Giyani market" },
      { who: "@nutrition_za", text: "Protein content is genuinely excellent" },
    ],
    tags: ["masonja", "Limpopo", "protein"],
    link: { section: "food", slug: "masonja", label: "Get the recipe" },
    seeded: true,
  },
  {
    id: "p-gumboot",
    handle: "@shaft.crew",
    name: "Shaft Crew",
    avatarSeed: "shaft",
    place: "Carletonville",
    province: "GP",
    caption: "Gumboot. Our grandfathers invented this underground because they were not allowed to speak.",
    kind: "culture",
    mediaKind: "video",
    duration: "1:50",
    likes: 58300,
    comments: [
      { who: "@mine_history", text: "The rhythm patterns were a code. People forget that." },
      { who: "@pieter", text: "The synchronisation is unreal" },
    ],
    tags: ["gumboot", "dance", "mines"],
    link: { section: "culture", slug: "gumboot", label: "About gumboot dance" },
    seeded: true,
  },
  {
    id: "p-sepitori",
    handle: "@pitori.talk",
    name: "Kgosi",
    avatarSeed: "kgosi",
    place: "Atteridgeville",
    province: "GP",
    caption: "Sepitori explained for people who think we are just speaking Setswana wrong.",
    body: "It is Setswana, Sepedi, Afrikaans and Tsotsitaal in one sentence. It has rules. You just do not know them.",
    kind: "language",
    mediaKind: "video",
    duration: "2:22",
    likes: 46700,
    comments: [
      { who: "@linguist_za", text: "Urban varieties are real languages. Thank you." },
      { who: "@tshepo", text: "'mo fise' 😂 accurate" },
    ],
    tags: ["Sepitori", "slang", "Pretoria"],
    link: { section: "languages", slug: "tsn", label: "Learn Setswana" },
    seeded: true,
  },
  {
    id: "p-stokvel",
    handle: "@mam.dudu",
    name: "Mam' Dudu",
    avatarSeed: "dudu",
    place: "Soweto",
    province: "GP",
    caption: "Our stokvel books from 1984. Minutes, fines, two signatures on the box.",
    body: "The banks did not want us so we made our own. The money was never the main thing. The meeting was the main thing.",
    kind: "story",
    mediaKind: "photo",
    duration: "—",
    likes: 61400,
    comments: [
      { who: "@fin_sa", text: "This is a better governance model than most companies" },
      { who: "@asanda", text: "Showing this to my group chat stokvel 😅" },
      { who: "@nomsa.b", text: "My mother's book is from 1979. I still have it." },
    ],
    tags: ["stokvel", "money", "Soweto"],
    link: { section: "stories", slug: "how-our-mothers-banked", label: "Read the full story" },
    elder: true,
    seeded: true,
  },
];

export const POST_BY_ID = Object.fromEntries(POSTS.map((p) => [p.id, p]));
