import type { Recipe } from "@/lib/types";

export const RECIPES: Recipe[] = [
  {
    slug: "umngqusho",
    name: "Umngqusho",
    aka: ["Samp and beans", "Setampa", "Stampmielies"],
    region: "Eastern Cape, and nationwide",
    province: "EC",
    kind: "staple",
    time: "Soak overnight, then 2½–3 hours",
    serves: "6–8",
    heat: "Mild",
    story:
      "Umngqusho is crushed white maize cooked slowly with sugar beans until the whole pot goes soft and creamy. It is the signature dish of the Eastern Cape and was famously Nelson Mandela's favourite food — he wrote about eating it as a boy in Qunu and asked for it in prison. It is cheap, it is filling, and it is the dish most often cited when South Africans abroad say they are homesick. The trick is patience: umngqusho cannot be rushed, and anyone who tells you they made it in an hour made something else.",
    ingredients: [
      { group: "The base", items: ["2 cups samp (crushed white maize)", "1 cup sugar beans", "Water to cover, plus more as it cooks", "1 tsp salt"] },
      { group: "The flavour", items: ["1 large onion, chopped", "2 tbsp butter or beef dripping", "1 beef or chicken stock cube", "1 tsp paprika", "Black pepper"] },
      { group: "Optional, if it is a Sunday", items: ["Chopped tomatoes", "A piece of smoked meat or a marrow bone", "Fresh chilli"] },
    ],
    method: [
      "Rinse the samp and the beans well, then soak them together in plenty of cold water overnight. Do not skip this.",
      "Drain, put them in a heavy pot and cover with fresh water by about three fingers.",
      "Bring to the boil, then turn down to a slow simmer and leave it. Check every 30 minutes and top up with hot water so it never catches.",
      "After about two hours the samp should be splitting open and the beans going soft. Add salt only now — salt added early keeps beans hard.",
      "Fry the onion in the butter until deep golden, add paprika and stock cube, then stir it through the pot.",
      "Cook another 20–30 minutes until the mixture is thick and creamy, and some of the samp has broken down into the liquid. Taste for salt and pepper.",
    ],
    serveWith: ["Umleqwa or any stew", "Chakalaka", "A spoon of sour milk (amasi)", "Spinach or morogo on the side"],
    tip: "If you have a marrow bone, put it in from the start. The marrow dissolves into the pot and is the single biggest upgrade you can make.",
    tags: ["maize", "beans", "slow cooked", "Eastern Cape"],
  },
  {
    slug: "pap-en-vleis",
    name: "Pap and Shisa Nyama",
    aka: ["Pap en vleis", "Phuthu", "Braaivleis"],
    region: "Nationwide, with a strong Gauteng township tradition",
    province: "GP",
    kind: "feast",
    time: "45 minutes plus fire time",
    serves: "4–6",
    heat: "Depends on the chakalaka",
    story:
      "Shisa nyama literally means 'burn the meat' in isiZulu. In townships across the country it describes a specific institution: a butchery with a fire out front, where you buy raw meat by the kilo, hand it over, and it is grilled while you stand around with a drink and extremely loud music. Pap — stiff maize porridge — is the compulsory partner. The relationship between the pap, the meat and the gravy is the entire point, and every family has a position on how stiff the pap should be.",
    ingredients: [
      { group: "Pap (stiff)", items: ["4 cups water", "1 tsp salt", "2½ cups white maize meal"] },
      { group: "The meat", items: ["Boerewors (a coil, never cut into pieces before cooking)", "Beef short rib or lamb chops", "Chicken portions", "Coarse salt, black pepper, a braai spice rub"] },
      { group: "The gravy (sheba)", items: ["2 onions, sliced", "3 tomatoes, grated", "1 green pepper", "1 tbsp tomato paste", "Oil, salt, pepper, a pinch of sugar"] },
    ],
    method: [
      "Get the fire going first and let it burn down to coals. Never cook over flames — you want grey coals with a red glow underneath.",
      "For the pap: bring salted water to the boil, pour the maize meal in the middle in one go, do not stir. Let it sit for 2 minutes, then turn the heat right down, cover and steam for 10 minutes.",
      "Now stir it hard with a wooden spoon to break it up, cover again and steam another 20–30 minutes on the lowest heat, stirring occasionally. It should hold its shape on a plate.",
      "For sheba: fry onions until soft, add green pepper, then grated tomato, tomato paste, a pinch of sugar, salt and pepper. Simmer 15 minutes until thick and glossy.",
      "Braai the wors whole over medium coals, turning once, until it is firm and springy — about 20 minutes. Do not pierce it.",
      "Braai the chops and rib over hotter coals, chicken over cooler coals and for longer. Rest the meat before cutting.",
    ],
    serveWith: ["Chakalaka", "Atchar", "Sour milk", "Grilled mielies"],
    tip: "Pap is judged by whether it holds a dent from your thumb. Too soft and it is phuthu for breakfast, not pap for meat.",
    tags: ["braai", "maize", "meat", "weekend"],
  },
  {
    slug: "chakalaka",
    name: "Chakalaka",
    aka: ["Chaka"],
    region: "Johannesburg townships, now nationwide",
    province: "GP",
    kind: "staple",
    time: "30 minutes",
    serves: "6",
    heat: "Medium to hot — your call",
    story:
      "Chakalaka is a spicy vegetable relish that most accounts trace to the mine hostels and townships around Johannesburg, where workers combined cheap vegetables, curry powder and tinned beans into something that could make a mountain of pap interesting. It is now on every braai table in the country, sold in tins in supermarkets, and served at state banquets. Everyone's recipe is different and everyone's is correct, but it must have carrots and it must have heat.",
    ingredients: [
      { group: "Base", items: ["2 tbsp oil", "1 large onion, finely chopped", "2 cloves garlic", "1 tbsp grated ginger", "2 green chillies (or more)"] },
      { group: "Vegetables", items: ["4 carrots, coarsely grated", "1 red and 1 green pepper, diced", "2 tomatoes, grated", "1 tin baked beans in tomato sauce"] },
      { group: "Spice", items: ["2 tbsp mild curry powder", "1 tsp paprika", "1 tsp thyme", "Salt and pepper", "Pinch of sugar"] },
    ],
    method: [
      "Fry the onion in oil until translucent, then add garlic, ginger and chilli and cook for a minute until fragrant.",
      "Add the curry powder and paprika and fry for 30 seconds — this wakes up the spice and is the step most people skip.",
      "Add peppers and cook for 3 minutes, keeping some bite.",
      "Add the grated carrot and stir well. Cook 5 minutes.",
      "Add grated tomato, thyme, salt, pepper and sugar. Simmer 10 minutes until the liquid reduces.",
      "Stir in the tin of baked beans and warm through for 5 minutes. Do not boil it to mush — chakalaka should still have texture.",
    ],
    serveWith: ["Pap", "Braai meat", "Bread", "Umngqusho", "Cold, straight from the fridge the next day"],
    tip: "It is better on day two. Make it the night before the braai.",
    tags: ["relish", "spicy", "vegetables", "braai"],
  },
  {
    slug: "bunny-chow",
    name: "Bunny Chow",
    aka: ["Bunny", "Quarter", "Kota (the Gauteng cousin)"],
    region: "Durban",
    province: "KZN",
    kind: "street",
    time: "1½ hours",
    serves: "4 quarters",
    heat: "Hot",
    story:
      "A bunny chow is a hollowed-out loaf of white bread filled with curry. It comes from Durban's Indian community, and the most widely repeated account is that it was created so that workers who were not permitted to be served inside restaurants under segregation could be handed a portable meal — the bread was the container and the plate. You order by size: a quarter, a half or a full loaf. There is no cutlery. The 'virgin' — the lid cut off the loaf — is used to scoop, and is eaten last after it has soaked up the gravy.",
    ingredients: [
      { group: "Curry", items: ["1 kg mutton on the bone (or chicken, or beans)", "2 onions, finely chopped", "2 tbsp Durban masala", "1 tsp turmeric", "1 tsp cumin seeds", "2 cardamom pods, 1 cinnamon stick, 2 bay leaves", "4 tomatoes, grated", "4 potatoes, quartered", "Ginger and garlic paste", "Curry leaves", "Salt"] },
      { group: "To serve", items: ["1 unsliced white loaf", "Carrot sambal", "Fresh coriander"] },
    ],
    method: [
      "Heat oil and fry the whole spices — cinnamon, cardamom, cumin, bay, curry leaves — until they crackle.",
      "Add onions and fry slowly until deep brown. This takes longer than you think and decides the colour of the final curry.",
      "Add ginger and garlic, then the masala and turmeric. Fry 1 minute with a splash of water so it does not burn.",
      "Add the meat and seal it in the spice, stirring to coat every piece. Add salt.",
      "Add grated tomato, cover and simmer on low for 45 minutes, stirring occasionally. Add water only if it threatens to catch.",
      "Add potatoes and cook another 25–30 minutes until the meat falls off the bone and the potatoes are soft enough to break.",
      "Cut the loaf into quarters. Hollow each quarter out, keeping the bread you remove as the 'virgin'. Fill generously with curry and gravy, place the virgin on top.",
    ],
    serveWith: ["Carrot sambal", "Chilli on the side", "No cutlery"],
    tip: "The gravy must be thick enough to stay in the bread. If it runs out of the bottom you have made soup in a loaf.",
    tags: ["Durban", "curry", "street food", "Indian South African"],
  },
  {
    slug: "amagwinya",
    name: "Amagwinya",
    aka: ["Vetkoek", "Magwinya", "Fat cakes", "Dippeldoppies"],
    region: "Nationwide",
    province: "NAT",
    kind: "street",
    time: "2 hours including proving",
    serves: "Makes about 16",
    heat: "None",
    story:
      "Deep-fried dough, crisp outside and soft inside, sold from buckets on every corner in the country at breakfast time. Afrikaans speakers call them vetkoek, isiZulu and Sesotho speakers call them amagwinya or magwinya, and the Gauteng street version is almost always split and filled with polony, cheese, atchar or curried mince. They cost very little, they are everywhere, and more South Africans eat these for breakfast than eat cereal.",
    ingredients: [
      { group: "Dough", items: ["4 cups cake flour", "1 packet (10 g) instant yeast", "1 tsp salt", "2 tbsp sugar", "About 1½ cups warm water", "Oil for deep frying"] },
      { group: "Fillings", items: ["Curried mince", "Polony and cheese", "Atchar", "Jam and butter", "Tinned fish"] },
    ],
    method: [
      "Mix flour, yeast, salt and sugar in a big bowl.",
      "Add warm water gradually and mix to a soft, slightly sticky dough. Knead 8 minutes until smooth and elastic.",
      "Cover with a cloth and leave in a warm place for about an hour, until doubled.",
      "Knock the dough down and pull off pieces the size of a small fist. Shape into rounds and let them rest 15 minutes.",
      "Heat oil to medium — about 170°C. Too hot and you get a raw middle; this is the most common mistake.",
      "Fry in batches, turning once, for 4–5 minutes until deep golden brown and hollow-sounding. Drain on paper.",
      "Split while warm and fill.",
    ],
    serveWith: ["Curried mince", "Atchar", "Sweet tea"],
    tip: "Test the oil with a small ball of dough. It should rise within three seconds and brown in about four minutes.",
    tags: ["breakfast", "street food", "fried", "cheap"],
  },
  {
    slug: "umleqwa",
    name: "Umleqwa",
    aka: ["Hard-body chicken", "Running chicken", "Inkukhu yasekhaya"],
    region: "Rural Eastern Cape and KwaZulu-Natal",
    province: "EC",
    kind: "feast",
    time: "2½–3 hours",
    serves: "6",
    heat: "Mild",
    story:
      "Umleqwa means roughly 'the one that is chased'. It is free-range village chicken — a bird that has spent its life running around the yard, which makes the meat dark, dense and enormously flavourful, and also makes it tough as rope if you cook it like a supermarket chicken. Umleqwa is a special-occasion dish: it is what you slaughter for a visitor who matters. The cooking method is the opposite of a roast chicken — long, wet and slow.",
    ingredients: [
      { group: "Chicken", items: ["1 free-range village chicken, cut into pieces", "2 onions, chopped", "3 tomatoes, grated", "2 tbsp oil", "Salt and black pepper", "1 beef stock cube", "2 bay leaves", "Fresh thyme"] },
      { group: "Optional", items: ["1 tsp curry powder", "Potatoes", "Fresh chilli"] },
    ],
    method: [
      "Wash the chicken pieces well. Put them in a heavy pot with water to barely cover, add salt and bay leaves.",
      "Bring to the boil, skim the foam off the top, then turn down to a low simmer and cook — covered — for a full 1½ to 2 hours. This is not optional. The connective tissue has to break down.",
      "Test with a fork. When the meat gives easily but still holds on the bone, lift the pieces out and keep the broth.",
      "In another pot, fry the onions in oil until golden. Add grated tomato, stock cube, thyme and pepper and cook down for 10 minutes.",
      "Return the chicken to the sauce with enough of the reserved broth to come halfway up. Simmer uncovered 30 minutes so the sauce thickens and coats the meat.",
      "Taste. Village chicken takes more salt than you expect.",
    ],
    serveWith: ["Umngqusho", "Pap", "Dombolo", "Spinach"],
    tip: "Never throw away the first broth. It is the best chicken stock you will ever have, and it is what makes the sauce.",
    tags: ["chicken", "slow cooked", "special occasion", "rural"],
  },
  {
    slug: "dombolo",
    name: "Dombolo",
    aka: ["Ujeqe", "Steamed bread", "Idombolo", "Dumpling"],
    region: "Nationwide",
    province: "NAT",
    kind: "staple",
    time: "2½ hours",
    serves: "8",
    heat: "None",
    story:
      "Dombolo is a large yeasted bread steamed rather than baked — traditionally in a cloth or a tin inside a pot of boiling water, often set inside the stew it will be eaten with. The result is dense, slightly sweet, pale and almost cake-soft, perfect for mopping gravy. It is Sunday lunch food, and in many households the steaming pot on the stove is the smell that means the family is coming over.",
    ingredients: [
      { group: "Dough", items: ["6 cups cake flour", "1 packet (10 g) instant yeast", "2 tbsp sugar", "2 tsp salt", "About 2½ cups lukewarm water", "2 tbsp oil"] },
      { group: "For steaming", items: ["A large pot with a lid", "A heatproof bowl or clean empty tin", "A cloth"] },
    ],
    method: [
      "Combine flour, yeast, sugar and salt. Add oil and warm water and mix to a soft dough.",
      "Knead 10 minutes until smooth. Cover and prove in a warm spot for about an hour until doubled.",
      "Grease a heatproof bowl or large tin. Knock the dough down, shape it, and put it in — it should fill no more than two-thirds.",
      "Cover the bowl with a cloth and let it rise again for 30 minutes.",
      "Put a saucer or a ring of foil at the bottom of a large pot, add boiling water to come a third of the way up the bowl, and set the bowl in.",
      "Cover with the lid and steam on a steady medium heat for 1 to 1½ hours. Do not lift the lid in the first hour or it will collapse.",
      "Test with a skewer. Turn out and cut thick slices.",
    ],
    serveWith: ["Any stew with a lot of gravy", "Umleqwa", "Mogodu", "Beef short rib"],
    tip: "Steam it directly on top of the stew if your pot is big enough. The bread takes on the flavour of what is underneath it.",
    tags: ["bread", "steamed", "Sunday", "stew"],
  },
  {
    slug: "mogodu",
    name: "Mogodu",
    aka: ["Tripe", "Ulusu", "Afval"],
    region: "Nationwide",
    province: "NAT",
    kind: "staple",
    time: "3–4 hours",
    serves: "6",
    heat: "Mild",
    story:
      "Mogodu is tripe — the stomach lining of a cow — cleaned, boiled for hours and stewed down until it is soft and gelatinous. It divides people violently, and the people who love it love it with total conviction. It is traditionally associated with Thursday in parts of Gauteng, where Thursday was the domestic workers' day off and mogodu was the cheap, slow-cooked dish of the day. Many taverns still sell it on a Thursday for exactly that reason.",
    ingredients: [
      { group: "Tripe", items: ["1.5 kg cleaned beef tripe, cut into squares", "2 onions, chopped", "2 bay leaves", "1 tbsp coarse salt", "Water to cover"] },
      { group: "Sauce", items: ["2 tbsp oil", "3 tomatoes, grated", "1 tbsp curry powder", "1 tsp paprika", "2 cloves garlic", "1 beef stock cube", "Black pepper", "Fresh chilli to taste"] },
    ],
    method: [
      "Rinse the tripe repeatedly in cold water until the water runs clear. Cleaning properly is the whole battle.",
      "Put it in a large pot with water, salt, bay leaves and one chopped onion. Boil hard for 10 minutes, then drain and rinse again.",
      "Cover with fresh water and simmer, covered, for 2½ to 3 hours until a fork goes through easily.",
      "Fry the second onion with garlic, add curry powder and paprika, then grated tomato and stock cube. Cook down 15 minutes.",
      "Add the drained tripe with a cup of its cooking liquid. Simmer uncovered 30–40 minutes until thick.",
      "Season heavily with black pepper. Add chilli at the end.",
    ],
    serveWith: ["Pap", "Dombolo", "Chakalaka", "Spinach"],
    tip: "Pressure cooker: 45 minutes instead of three hours. Purists will object; your Thursday will be better.",
    tags: ["offal", "slow cooked", "Thursday", "tavern"],
  },
  {
    slug: "morogo",
    name: "Morogo",
    aka: ["Imifino", "Miroho", "Wild spinach", "African leafy greens"],
    region: "Nationwide, especially rural",
    province: "NAT",
    kind: "wild",
    time: "25 minutes",
    serves: "4",
    heat: "None",
    story:
      "Morogo is not one plant. It is a category: wild and semi-wild leafy greens gathered from the fields, including amaranth (thepe), cowpea leaves, pumpkin leaves (leroto / imibhida), blackjack (mushidzhi) and spider plant. These grow as weeds between crops, which means they arrive free with farming, and they are nutritionally dense — research on African leafy vegetables has repeatedly found them higher in iron, calcium and vitamin A than commercial spinach. Gathering morogo was women's and children's work and the knowledge of which leaves to pick is real, local botany that is being lost fast.",
    ingredients: [
      { group: "Greens", items: ["2 large bunches of morogo (amaranth, pumpkin leaves, cowpea leaves or a mix)", "1 onion, chopped", "2 tbsp oil or butter", "Salt"] },
      { group: "Optional", items: ["1 tomato, grated", "Peanut butter (1 tbsp — traditional in parts of Limpopo)", "Chilli"] },
    ],
    method: [
      "Strip the leaves from any tough stems. Wash in several changes of water — these grow in fields and the grit is real.",
      "Chop roughly.",
      "Fry the onion in oil until soft and just starting to colour.",
      "Add the wet leaves with no extra water. Cover and let them wilt down for 5 minutes.",
      "Uncover, season with salt, and cook 10–15 minutes until tender and the liquid has reduced.",
      "For the Limpopo style, stir a spoon of peanut butter through at the end until it melts into a thick sauce.",
    ],
    serveWith: ["Pap", "Umngqusho", "Any meat", "Sour milk"],
    tip: "Do not add water. The leaves hold plenty and extra water boils away the flavour and the nutrients with it.",
    tags: ["vegetables", "foraged", "healthy", "traditional"],
  },
  {
    slug: "umqombothi",
    name: "Umqombothi",
    aka: ["Traditional beer", "Joala", "Byalwa", "Utshwala"],
    region: "Nationwide",
    province: "NAT",
    kind: "drink",
    time: "3–5 days",
    serves: "Makes about 10 litres",
    heat: "None",
    story:
      "Umqombothi is traditional beer brewed from maize meal and sorghum malt. It is low in alcohol, thick, sour, pinkish-brown, and it is never only a drink: it is brewed for ceremonies, for ancestors, for weddings and for the welcoming of visitors. In many traditions beer is poured for the ancestors before anyone drinks, and the clay pot is passed in order of seniority. Brewing it is a skill held mostly by older women, and a brewer with a good reputation is a person of real standing in a community.",
    ingredients: [
      { group: "Brew", items: ["2 kg maize meal", "1 kg sorghum malt (umthombo)", "5 litres warm water, plus more", "A large clay pot or plastic drum", "A clean cloth"] },
    ],
    method: [
      "Mix the maize meal with warm water into a thin porridge and leave covered overnight to sour.",
      "Cook the soured porridge gently for about an hour, stirring, then let it cool to lukewarm. If it is too hot it will kill the ferment.",
      "Stir in the sorghum malt thoroughly.",
      "Cover with a cloth and leave in a warm place for 2 to 3 days. It will foam, hiss and smell sharply sour. That is correct.",
      "Strain through a sieve or cloth to remove the coarse grain.",
      "Serve the same day in a clay pot (ukhamba). It keeps fermenting, so it changes character by the hour.",
    ],
    serveWith: ["Served first to the eldest", "Poured for the ancestors before drinking", "Meat from a ceremony"],
    tip: "Umqombothi is alive. It is at its best on the day it is strained and it will be sour and much stronger by day two.",
    tags: ["ceremony", "brewing", "ancestors", "drink"],
  },
  {
    slug: "masonja",
    name: "Masonja",
    aka: ["Mopane worms", "Madora", "Amacimbi", "Mashonzha"],
    region: "Limpopo, Mpumalanga, North West",
    province: "LP",
    kind: "wild",
    time: "40 minutes (if dried)",
    serves: "4 as a side",
    heat: "Medium",
    story:
      "Masonja are the caterpillars of the emperor moth, harvested from mopane trees in the northern provinces. They are gutted, boiled in salt water and dried in the sun, which turns them into a shelf-stable, protein-dense food that keeps for months without refrigeration. Harvesting is a seasonal industry supporting large numbers of rural households, mostly women. Dried masonja are sold by the bucket in markets across Limpopo and Gauteng. They taste savoury and earthy, somewhere between dried mushroom and biltong.",
    ingredients: [
      { group: "Worms", items: ["2 cups dried mopane worms", "Water for rehydrating"] },
      { group: "Sauce", items: ["1 onion, chopped", "2 tomatoes, grated", "2 tbsp oil", "1 tsp curry powder", "Fresh chilli", "Salt"] },
    ],
    method: [
      "Rinse the dried worms and soak in warm water for about 20 minutes until they soften and plump up.",
      "Drain and squeeze out the excess water.",
      "Fry the onion in oil until golden, add curry powder and chilli.",
      "Add the worms and fry for 5 minutes so they take on colour and crisp slightly at the edges.",
      "Add grated tomato and salt and simmer 10 minutes until the sauce clings.",
      "They can also be eaten dry and plain as a snack, straight from the bag, like biltong.",
    ],
    serveWith: ["Pap", "Morogo", "Eaten dry as a snack"],
    tip: "If you are trying them for the first time, have them fried crisp with chilli rather than wet in a sauce. The texture is much easier.",
    tags: ["protein", "foraged", "Limpopo", "seasonal"],
  },
  {
    slug: "bobotie",
    name: "Bobotie",
    aka: ["Boboti"],
    region: "Cape Town — Cape Malay",
    province: "WC",
    kind: "feast",
    time: "1½ hours",
    serves: "6",
    heat: "Mild, sweet-spiced",
    story:
      "Bobotie is spiced minced meat baked under a savoury egg custard, with dried fruit through it and bay or lemon leaves standing up in the top. It comes from the Cape Malay kitchen — the cooking created by people enslaved and exiled to the Cape from Southeast Asia, India and East Africa from the 1600s onwards, whose descendants built an entire cuisine out of imported spice knowledge and local ingredients. Along with koesisters, denningvleis and sosaties, bobotie is one of the dishes that made the Cape Malay kitchen foundational to South African food.",
    ingredients: [
      { group: "Meat", items: ["1 kg beef or lamb mince", "2 onions, chopped", "2 slices white bread", "1 cup milk", "2 tbsp mild curry powder", "1 tsp turmeric", "2 tbsp chutney", "2 tbsp apricot jam", "1 tbsp vinegar", "½ cup raisins or sultanas", "Salt and pepper"] },
      { group: "Custard topping", items: ["2 eggs", "1 cup milk", "Pinch of salt", "6 bay leaves or lemon leaves"] },
    ],
    method: [
      "Soak the bread in the milk and set aside. Heat the oven to 180°C.",
      "Fry the onions until soft and golden, add curry powder and turmeric and cook 1 minute.",
      "Add the mince and brown well, breaking up lumps.",
      "Squeeze the milk out of the bread (keep the milk) and crumble the bread into the meat. Add chutney, jam, vinegar, raisins, salt and pepper. Simmer 10 minutes.",
      "Pack into a greased oven dish and press down flat.",
      "Beat the eggs with the reserved milk plus the extra cup, pour over the meat, and stand the bay leaves upright in the surface.",
      "Bake 35–40 minutes until the custard is set and lightly browned.",
    ],
    serveWith: ["Yellow rice with raisins", "Sambals — diced tomato and onion", "Chutney", "Sliced banana"],
    tip: "The sweet-sour balance is the dish. If it tastes flat, it needs vinegar, not salt.",
    tags: ["Cape Malay", "baked", "spiced", "Western Cape"],
  },
  {
    slug: "koesister",
    name: "Koesisters and Koeksisters",
    aka: ["Koe'sister", "Koeksuster"],
    region: "Cape Town and the interior",
    province: "WC",
    kind: "sweet",
    time: "2 hours",
    serves: "Makes about 20",
    heat: "None",
    story:
      "Two different things, one confusing pair of names. The Cape Malay koesister is a spiced, yeasted, oval dumpling — fried, dipped in syrup and rolled in coconut, soft and warm, traditionally made on a Sunday morning in Bo-Kaap and sold door to door. The Afrikaans koeksister is a plaited strip of dough deep-fried and plunged into ice-cold syrup until it is glassy, crunchy and extremely sweet. Confusing them in the wrong kitchen will start an argument. This recipe is the Cape Malay koesister.",
    ingredients: [
      { group: "Dough", items: ["4 cups flour", "1 packet instant yeast", "½ cup sugar", "1 tsp salt", "2 tsp ground cinnamon", "1 tsp ground ginger", "1 tsp mixed spice", "½ tsp cardamom", "1 cup warm milk", "2 tbsp butter, melted", "1 egg"] },
      { group: "Syrup and coating", items: ["2 cups sugar", "1 cup water", "1 stick cinnamon", "Strip of orange peel", "2 cups desiccated coconut"] },
    ],
    method: [
      "Mix flour, yeast, sugar, salt and all the spices. Add warm milk, melted butter and egg and knead to a soft dough.",
      "Cover and prove 1 hour until doubled.",
      "Shape into ovals about the size of an egg. Rest 20 minutes on a floured tray.",
      "Deep fry at a moderate heat, turning, until deep golden all the way through — about 5 minutes. The spice makes them look darker than they are, so check one.",
      "Boil the sugar, water, cinnamon and orange peel for 5 minutes to make a thin syrup.",
      "Dip each hot koesister into the warm syrup for a few seconds, lift out, and roll immediately in coconut.",
    ],
    serveWith: ["Hot tea", "Sunday morning", "Warm, within the hour"],
    tip: "Syrup warm, koesister hot. If either one is cold it will not soak properly.",
    tags: ["Cape Malay", "sweet", "Sunday", "Bo-Kaap"],
  },
  {
    slug: "potjiekos",
    name: "Potjiekos",
    aka: ["Potjie", "Three-legged pot stew"],
    region: "Nationwide",
    province: "NAT",
    kind: "feast",
    time: "3–4 hours",
    serves: "8",
    heat: "Mild",
    story:
      "A potjie is a round cast-iron pot with three legs that stands directly in the coals. Potjiekos is what you cook in it, and it has one near-religious rule: you do not stir it. Ingredients go in in layers, in order of cooking time, and they stay in those layers so that each one keeps its own texture and the flavours move downward through the pot. Making a potjie takes an afternoon, which is the real point — it is a social event disguised as a cooking method, and the cook is expected to stand next to it the entire time.",
    ingredients: [
      { group: "Meat layer", items: ["1.5 kg beef shin, oxtail or lamb knuckle", "2 onions", "Oil", "Salt and pepper", "1 cup red wine or stock"] },
      { group: "Layers on top", items: ["Carrots, thick chunks", "Potatoes, halved", "Baby marrow", "Green beans", "Mushrooms", "Sweet potato"] },
      { group: "Seasoning", items: ["Bay leaves", "Thyme", "Garlic", "1 packet brown onion soup powder (the open secret)"] },
    ],
    method: [
      "Get coals going. You want a low, steady heat under the pot — never flames.",
      "Heat oil in the potjie and brown the meat hard, in batches. Do not crowd it.",
      "Add onions and cook until soft, then add wine or stock, bay and thyme. Put the lid on and let the meat alone for 2 hours, checking the liquid now and then.",
      "Now layer the vegetables on top, hardest and slowest first: carrots, then potatoes, then sweet potato, then the quick ones — marrow, beans, mushrooms — on top.",
      "Do not stir. Put the lid back and cook 1 to 1½ hours more.",
      "Only at the very end, lift the pot off the coals, sprinkle the soup powder over, and stir once — just once — to bring the gravy together.",
    ],
    serveWith: ["Rice", "Pap", "Crusty bread", "Several hours of conversation"],
    tip: "Keep the coals small and constant. Most failed potjies are burnt on the bottom because somebody kept feeding the fire.",
    tags: ["potjie", "fire", "slow cooked", "social"],
  },
];

export const RECIPE_BY_SLUG = Object.fromEntries(RECIPES.map((r) => [r.slug, r]));

export const RECIPE_KINDS: { id: Recipe["kind"]; label: string }[] = [
  { id: "staple", label: "Everyday staples" },
  { id: "feast", label: "Feast & Sunday" },
  { id: "street", label: "Street food" },
  { id: "wild", label: "Foraged & wild" },
  { id: "drink", label: "Drinks" },
  { id: "sweet", label: "Sweet" },
];
