import type { Game } from "@/lib/types";

export const GAMES: Game[] = [
  {
    slug: "diketo",
    name: "Diketo",
    aka: [
      { lang: "isiZulu / isiXhosa", name: "Upuca" },
      { lang: "Xitsonga", name: "Magave" },
      { lang: "Sepedi", name: "Diketo" },
      { lang: "Tshivenda", name: "Mufuvha wa maṱe" },
    ],
    tagline: "Ten stones, one hole, and hands faster than gravity.",
    players: "2–6, taking turns",
    ages: "6 and up",
    kit: ["10 small stones (amatshe)", "1 larger 'mother' stone (ghoen)", "A shallow scooped hole in the ground"],
    provinces: ["NAT"],
    about:
      "Diketo is the stone game that almost every South African child who grew up before smartphones can still play with their eyes closed. It needs nothing you have to buy: a patch of ground, a handful of pebbles and a scooped hole. It trains counting, hand-eye coordination and nerve — and because the hole is dug fresh each time, the 'board' belongs to whoever is playing. It is often played by girls in a circle, with the rest of the group counting out loud and arguing about whether a stone really touched.",
    how: [
      "Scoop a shallow hole in the sand, about the width of your palm.",
      "Put the ten small stones in the hole. Keep the big 'mother' stone in your throwing hand.",
      "Throw the mother stone straight up. While it is in the air, sweep ONE stone out of the hole — then catch the mother stone before it lands.",
      "Throw again, and this time put that stone back IN. Catch.",
      "Round two: take out two stones at a time. Then three. Then four — all the way to ten.",
      "Any drop, any miss, any wrong count — your turn ends and the next player starts from round one.",
    ],
    rules: [
      "The mother stone may never touch the ground.",
      "You scoop with one hand only; the other hand stays behind your back.",
      "If you move a stone you did not mean to move, you are out — the watchers will tell you.",
      "First player to complete all ten rounds wins the round, and usually the right to dig the next hole.",
    ],
    variations: [
      { place: "KwaZulu-Natal (as upuca)", text: "Played on a flat stone or step rather than in sand, so the stones slide instead of being scooped." },
      { place: "Limpopo", text: "A larger set of up to twenty seeds is used, and players chant the count in Sepedi to keep tempo." },
      { place: "Gauteng townships", text: "Played on a concrete stoep with marbles or bottle tops instead of stones; the hole becomes a chalk circle." },
      { place: "Western Cape", text: "Known locally alongside klip-klip; knucklebones from a sheep are sometimes used in place of pebbles." },
    ],
    challenge: { title: "Ten in one breath", brief: "Film yourself clearing all ten rounds without dropping the mother stone. No cuts.", xp: 250 },
    playable: "diketo",
    demo: "Watch the hands, not the stone — good players never look at what they are picking up.",
    tags: ["dexterity", "no equipment", "playground"],
  },
  {
    slug: "morabaraba",
    name: "Morabaraba",
    aka: [
      { lang: "isiZulu", name: "Umlabalaba" },
      { lang: "Sesotho / Setswana", name: "Morabaraba" },
      { lang: "Xitsonga", name: "Muravarava" },
      { lang: "English", name: "Twelve Men's Morris" },
    ],
    tagline: "The cattle game. Herd boys invented the strategy board that beat chess to the kraal.",
    players: "2",
    ages: "8 and up",
    kit: ["A board of 24 points drawn in the sand or burnt into wood", "12 'cows' per player — stones, bottle tops or seeds"],
    provinces: ["NAT"],
    about:
      "Morabaraba was played by herd boys watching cattle, scratched into the dust with a stick while the animals grazed. Your pieces are literally your cows, and a line of three is a 'mill' that lets you shoot one of your opponent's cows. It is a genuinely deep strategy game — openings, traps and endgames are argued about the way chess players argue — and it is recognised as a South African sporting code with national tournaments and its own federation.",
    how: [
      "Draw three nested squares joined by lines through the middle of each side, plus four diagonals linking the corners. That gives 24 points.",
      "PLACING: take turns putting one cow at a time on any empty point, until both players have placed all 12 cows.",
      "MOVING: now slide a cow along a line to an adjacent empty point, one move each turn.",
      "A MILL is three of your cows in a straight line along a drawn line. Every time you make one, you 'shoot' (remove) one enemy cow.",
      "FLYING: when you are down to three cows, you may jump to any empty point on the board.",
      "You lose when you are down to two cows, or when you cannot make a legal move.",
    ],
    rules: [
      "You may not shoot a cow that is already inside a mill, unless every enemy cow is in a mill.",
      "Opening a mill and closing it again on the next turn is legal, and it is the backbone of expert play.",
      "Twenty-four cows fill all twenty-four points exactly — so the only way the moving phase can happen is if mills were made during placement.",
      "The four diagonals are part of the South African board. This is what makes morabaraba twelve-man, not the nine-man version played in Europe.",
    ],
    variations: [
      { place: "Lesotho and Free State", text: "Some households allow shooting two cows when a single move completes two mills at once." },
      { place: "Eastern Cape", text: "Played with the rule that the first player must place their first cow on the centre point of a side." },
      { place: "Tournament play", text: "Organised competitive play standardises the no-diagonals board and bans shooting from a mill." },
    ],
    challenge: { title: "Beat the board", brief: "Win against the built-in opponent on Hard without losing more than three cows.", xp: 400 },
    playable: "morabaraba",
    demo: "The classic trap: build two mills sharing a pivot cow, then open and close it every single turn.",
    tags: ["strategy", "board game", "two player"],
  },
  {
    slug: "kgati",
    name: "Kgati",
    aka: [
      { lang: "isiZulu", name: "Ugqaphu" },
      { lang: "isiXhosa", name: "Ugqaphu" },
      { lang: "Sesotho / Setswana", name: "Kgati" },
      { lang: "Afrikaans", name: "Touspring" },
    ],
    tagline: "Two turners, one long rope, and a song that decides how fast you die.",
    players: "3 or more (two turning, the rest jumping)",
    ages: "6 and up",
    kit: ["A long rope — traditionally plaited from old stockings or plastic bags"],
    provinces: ["NAT"],
    about:
      "Kgati is skipping, but calling it skipping undersells it. Two players turn a long rope while the others jump in, and the whole thing is driven by call-and-response songs. The song sets the tempo, and the turners speed up on command — so the game is really a contest between the singers and the jumper's lungs. In many neighbourhoods the ropes were handmade: old pantyhose plaited together, or strips cut from plastic bags and twisted into a cord.",
    how: [
      "Two players hold the rope ends and turn it steadily in one direction.",
      "A jumper runs in on the beat without stopping the rope.",
      "Everyone sings. The jumper must keep going for the full verse.",
      "On the chorus the turners speed up — this is called 'the fire' in some places.",
      "You are out when the rope catches your feet. You then take over one of the turning ends.",
    ],
    rules: [
      "You may not stop the rope to get in — running in on the beat is half the skill.",
      "Whoever is caught becomes a turner, so the worst jumper turns the most.",
      "Advanced levels: jumping with two ropes, jumping in pairs, or jumping while doing a task like folding a cloth.",
    ],
    variations: [
      { place: "Soweto", text: "Jumpers must perform a named move each verse — a kick, a turn, a squat — called out by the turners." },
      { place: "Eastern Cape", text: "Sung in isiXhosa with clapping from the watchers, who act as judges for a clean jump." },
      { place: "Northern Cape", text: "Played with a single short rope per child in a line, racing to a fixed count." },
    ],
    challenge: { title: "Full verse, no catch", brief: "Record a full call-and-response verse with the rope at double tempo.", xp: 200 },
    demo: "Listen for the moment the turners drop the rope lower — that is the signal the tempo is about to break.",
    tags: ["rhythm", "team", "singing"],
  },
  {
    slug: "three-tins",
    name: "Three Tins",
    aka: [
      { lang: "isiXhosa", name: "Iitoti ezintathu" },
      { lang: "Afrikaans", name: "Blikkies" },
      { lang: "Kasi English", name: "Three tins / Tins" },
    ],
    tagline: "Knock the tower down, build it back up, and don't get hit.",
    players: "6–12, in two teams",
    ages: "7 and up",
    kit: ["3 empty tins or tin cans", "A soft ball — often a plastic bag bound with elastics"],
    provinces: ["NAT"],
    about:
      "Three Tins turns rubbish into equipment: three empty cans stacked into a tower and a ball made from a knotted plastic bag. One team tries to rebuild the tower after knocking it down, while the other team tries to hit them with the ball before they finish. It is pure township and village street play — the pitch is whatever space exists between the houses, and the boundaries are argued, loudly, every single round.",
    how: [
      "Stack the three tins into a tower in the middle of the playing area.",
      "The building team takes turns throwing the ball to knock the tower over from an agreed line.",
      "The moment the tower falls, the building team runs in to restack it.",
      "The fielding team grabs the ball and throws it at the builders — below the waist.",
      "A builder who is hit is out. If the tower gets restacked, the building team scores and plays again.",
    ],
    rules: [
      "Headshots do not count and usually cost the thrower a turn.",
      "Builders may dodge but may not hold or kick the ball away.",
      "If every builder is out before the tower is finished, the teams swap roles.",
    ],
    variations: [
      { place: "Cape Flats", text: "Played with a tennis ball and a chalk safe-zone the builders can stand in for three seconds." },
      { place: "Rural Limpopo", text: "Flat stones are stacked instead of tins, which makes rebuilding much harder." },
      { place: "KwaZulu-Natal", text: "A fourth tin is added for older players, and the throwing line is moved back a full stride." },
    ],
    challenge: { title: "Rebuild under fire", brief: "Restack all three tins solo while two fielders throw. Post the clip.", xp: 180 },
    demo: "The trick is to knock the tins sideways, not straight down — scattered tins take longer to find.",
    tags: ["running", "team", "recycled kit"],
  },
  {
    slug: "dibeke",
    name: "Dibeke",
    aka: [
      { lang: "Setswana", name: "Dibeke" },
      { lang: "isiZulu", name: "Skununu" },
      { lang: "Sepedi", name: "Mogusha" },
      { lang: "English", name: "Running ball" },
    ],
    tagline: "A whole-field running game where the ball is kicked by hand and defended by speed.",
    players: "12–24, two teams",
    ages: "10 and up",
    kit: ["A ball", "An open field with two end lines"],
    provinces: ["NAT"],
    about:
      "Dibeke is one of the codified South African indigenous games played at national level through school and provincial tournaments. Attackers try to get their whole team across the field and back while the defending team uses the ball to put them out. It is fast, exhausting and tactical — a kind of cousin to rounders and dodgeball with a distinctly local shape. Along with morabaraba, kgati, jukskei, diketo, ncuva, kho-kho and intonga, it forms the core set of games promoted by the national indigenous games programme.",
    how: [
      "Two teams: one attacking, one defending. Mark a start line and a far line.",
      "An attacker kicks the ball into the field using the side of the foot, then runs.",
      "The attacking team must cross to the far line and back without being put out.",
      "Defenders field the ball and hit running attackers with it to put them out.",
      "When all attackers are out, teams swap. Most completed crossings wins.",
    ],
    rules: [
      "Defenders may pass the ball between themselves to cut off a runner — running with the ball is limited.",
      "An attacker who is hit leaves the field until the next innings.",
      "A caught kick on the full puts the kicker out immediately.",
    ],
    variations: [
      { place: "North West", text: "Played with a fixed number of innings rather than until all attackers are out." },
      { place: "School tournaments", text: "Standardised field size and team of twelve, with referees and timed halves." },
    ],
    challenge: { title: "Full crossing", brief: "Record a complete there-and-back crossing without being hit.", xp: 220 },
    demo: "Attackers run in packs — a lone runner is an easy target for a two-defender pass.",
    tags: ["running", "team", "field"],
  },
  {
    slug: "masekitlana",
    name: "Masekitlana",
    aka: [
      { lang: "Sepedi / Setswana", name: "Masekitlana" },
      { lang: "Sesotho", name: "Masekitlane" },
    ],
    tagline: "Two stones, a rhythm on the ground, and a story only you can hear.",
    players: "1, or a small circle taking turns",
    ages: "4 and up",
    kit: ["Two stones that fit in the hand", "Hard ground"],
    provinces: ["LP", "NW", "GP", "FS"],
    about:
      "Masekitlana is the quietest game on this list and the strangest to explain. A child strikes two stones against the ground in a steady rhythm and, while doing it, tells a story out loud — usually one they are making up as they go. The stones become the characters. Because it gives children a way to narrate things they cannot say directly, South African psychologists have adapted masekitlana as a play-therapy technique for children who have experienced trauma, and it has been studied in that role at several local universities.",
    how: [
      "Sit on the ground with a stone in each hand.",
      "Strike one stone on the ground in a steady beat — the beat is the engine of the story.",
      "Begin narrating. The stones are people, cattle, taxis, whatever the story needs.",
      "Keep the rhythm going until the story ends. Dropping the beat usually ends the tale.",
      "In a circle, the next child picks up the story where the last one left it.",
    ],
    rules: [
      "There is no winner. The game ends when the story does.",
      "No one interrupts the storyteller — that is the whole etiquette of the game.",
    ],
    variations: [
      { place: "Limpopo", text: "Played with three stones, where the third is 'the one who listens' and never moves." },
      { place: "Therapeutic settings", text: "A facilitator sits nearby and only listens, never prompting, so the child keeps full control of the story." },
    ],
    challenge: { title: "One-take tale", brief: "Record a two-minute masekitlana story without breaking the rhythm.", xp: 300 },
    demo: "The beat is not decoration — storytellers use it to stall, speed up and signal that something bad is coming.",
    tags: ["storytelling", "solo", "rhythm"],
  },
  {
    slug: "ncuva",
    name: "Ncuva",
    aka: [
      { lang: "Xitsonga", name: "Ncuva" },
      { lang: "Sepedi", name: "Moruba" },
      { lang: "Tshivenda", name: "Mufuvha" },
      { lang: "English", name: "Sowing game (mancala family)" },
    ],
    tagline: "Rows of holes in the earth, a fistful of seeds, and arithmetic as warfare.",
    players: "2",
    ages: "9 and up",
    kit: ["Two or four rows of holes scooped in the ground", "Seeds, pebbles or marbles"],
    provinces: ["LP", "MP"],
    about:
      "Ncuva belongs to the great family of African sowing games found from Senegal to the Horn. Holes are scooped in the ground in rows, seeds are 'sown' around them, and you capture by landing in the right place at the right time. Elders play it under trees for hours; the board is often a permanent fixture at a homestead, worn smooth over decades. Because the rules differ from village to village, the first thing two strangers do is spend five minutes agreeing on whose rules they are playing.",
    how: [
      "Scoop two rows of holes per player — commonly 2 x 8 or 4 x 8 depending on the local rules.",
      "Place an agreed number of seeds in each hole.",
      "On your turn, lift all the seeds from one of your holes and sow them one by one into successive holes.",
      "If your last seed lands in a hole that then holds a capturing number, you take the seeds opposite.",
      "Play until one player can no longer move. The player holding the most seeds wins.",
    ],
    rules: [
      "Sowing direction must be agreed before the first move and never changes mid-game.",
      "You must always leave your opponent a legal move if you can.",
      "Captured seeds are kept out of play, not re-sown.",
    ],
    variations: [
      { place: "Xitsonga households", text: "Four rows per player, which makes the capture rules considerably more aggressive." },
      { place: "Sepedi (moruba)", text: "Often played on two rows with a fixed four seeds per hole at the start." },
      { place: "Tshivenda (mufuvha)", text: "Traditionally associated with adult men and played on a carved wooden board rather than in the ground." },
    ],
    challenge: { title: "Teach the rules", brief: "Film an elder explaining the capture rule as it is played in your area.", xp: 280 },
    demo: "Count the holes ahead before you lift — the best players have already seen three moves of sowing.",
    tags: ["strategy", "counting", "two player"],
  },
  {
    slug: "black-mampatile",
    name: "Black Mampatile",
    aka: [
      { lang: "isiZulu / isiXhosa", name: "Ndize" },
      { lang: "Setswana", name: "Black Mampatile" },
      { lang: "Afrikaans", name: "Wegkruipertjie" },
    ],
    tagline: "Hide and seek, played until a parent shouts your full name into the dark.",
    players: "4 or more",
    ages: "4 and up",
    kit: ["Nothing. A yard, a street, and somewhere to hide."],
    provinces: ["NAT"],
    about:
      "Every culture has hide and seek; South Africa has about nine names for it. Black Mampatile is the version played at dusk in townships and villages, when the light is going and the hiding places get genuinely good. The seeker counts at a 'home' point, and the thrill is not just hiding but the sprint to touch home before the seeker tags you. The game traditionally ends when the streetlights come on, or the moment someone's mother appears in a doorway.",
    how: [
      "Choose a seeker and a 'home' — a pole, a tree, a door.",
      "The seeker closes their eyes at home and counts out loud to an agreed number.",
      "Everyone else hides within the agreed boundary.",
      "The seeker hunts. Spotting someone is not enough — they must run back and touch home first, calling the name.",
      "A hider who reaches home untouched is safe. The first person caught becomes the next seeker.",
    ],
    rules: [
      "Boundaries are agreed before counting, and the argument about boundaries is part of the game.",
      "Hiders may move between hiding places while the seeker is away from home.",
      "If a hider touches home while the seeker is away, everyone already caught is freed.",
    ],
    variations: [
      { place: "Townships", text: "Played at dusk with a call-and-response shout so the seeker knows people are still alive out there." },
      { place: "Rural areas", text: "Much larger boundaries — whole sections of a village — and a longer count, often to one hundred." },
    ],
    challenge: { title: "Dusk run", brief: "Film the sprint for home. Bonus points if someone's gogo ends the game.", xp: 120 },
    demo: "Never hide far from home. The best hiders choose a spot with a clean running line.",
    tags: ["running", "evening", "no equipment"],
  },
  {
    slug: "jukskei",
    name: "Jukskei",
    aka: [
      { lang: "Afrikaans", name: "Jukskei" },
      { lang: "English", name: "Yoke-pin throwing" },
    ],
    tagline: "Throw a wooden yoke-pin down a sand pitch and knock out the peg.",
    players: "2 teams of up to 4",
    ages: "12 and up",
    kit: ["Wooden jukskeis (yoke pins)", "A peg", "A sand pitch"],
    provinces: ["NAT"],
    about:
      "Jukskei grew out of ox-wagon transport: the skei is the wooden pin that holds the yoke to the neck of an ox, and the story goes that transport riders threw spare pins at a peg in the sand at the end of a day's trek. It became a formal sport with national structures, standard pitch lengths and a scoring system, and it is one of the codes included in South Africa's national indigenous games programme. It is also one of the few games here played mostly by adults.",
    how: [
      "Push the peg into the sand at the far end of the pitch.",
      "Players throw their jukskei underarm, aiming to knock the peg out of the ground.",
      "Knocking the peg out scores the most points; otherwise the closest skei to the peg scores.",
      "Teams alternate throws until everyone has thrown.",
      "Play to an agreed total — commonly the first team to 23 points exactly.",
    ],
    rules: [
      "The throw must be underarm, with the skei held by the shaft.",
      "If a team goes over the target score, it drops back to a set figure — overshooting is punished.",
      "Measuring disputes are settled with a string from the peg.",
    ],
    variations: [
      { place: "Club play", text: "Standardised pitch lengths differ for men, women and juniors." },
      { place: "Informal play", text: "Any heavy stick and a tent peg will do, with the pitch paced out by foot." },
    ],
    challenge: { title: "Peg out", brief: "Knock the peg clean out of the sand and film the landing.", xp: 200 },
    demo: "Aim for the sand just in front of the peg — a skidding skei takes the peg out more reliably than a direct hit.",
    tags: ["throwing", "precision", "team"],
  },
  {
    slug: "intonga",
    name: "Intonga",
    aka: [
      { lang: "isiXhosa", name: "Intonga / Umwe" },
      { lang: "isiZulu", name: "Induku / Ukungcweka" },
      { lang: "English", name: "Stick fighting" },
    ],
    tagline: "The herd boys' martial art: two sticks, no armour, and a very old code of honour.",
    players: "2, with a referee and watchers",
    ages: "Traditionally boys from herding age; competitively 16 and up",
    kit: ["Two sticks — one to attack, one to defend", "In some traditions a small hide shield"],
    provinces: ["EC", "KZN"],
    about:
      "Stick fighting is the martial art of Nguni herd boys, learned in the veld while watching cattle and carried into adulthood as a mark of discipline. A fighter typically holds a defensive stick and a striking stick. It is governed by strict etiquette: you do not strike a man who is down, you accept the judgement of the watchers, and you greet your opponent afterwards. It appears at weddings and ceremonies as display rather than combat, and it is also run as a regulated competitive code with protective equipment at national indigenous games events.",
    how: [
      "Two fighters face off within a ring of watchers, who act as judges.",
      "Each holds a defending stick (held across the body) and a striking stick.",
      "Points are scored for clean strikes to the body; the head is governed by strict local rules.",
      "The watchers call the result. The fighters greet each other at the end — this is not optional.",
    ],
    rules: [
      "No striking an opponent who has lost their stick or gone down.",
      "The referee's call ends the exchange immediately.",
      "In competitive form, headgear and padding are required and target areas are restricted.",
    ],
    variations: [
      { place: "Eastern Cape", text: "Closely tied to herding culture and to the passage into manhood; display bouts are common at ceremonies." },
      { place: "KwaZulu-Natal", text: "Ukungcweka is performed at weddings and royal events, where the emphasis is display and respect rather than winning." },
      { place: "Competitive code", text: "Standardised equipment, weight classes and a scoring panel." },
    ],
    challenge: { title: "The greeting", brief: "Film the post-bout greeting and explain what the etiquette means where you are from.", xp: 260 },
    demo: "Watch the defending stick, not the striking one. Everything is decided by the block.",
    tags: ["martial art", "ceremony", "discipline"],
  },
];

export const GAME_BY_SLUG = Object.fromEntries(GAMES.map((g) => [g.slug, g]));
