import type { Language } from "@/lib/types";

/**
 * Home-language shares are drawn from Census 2022 (Statistics South Africa) and are
 * rounded. South Africa has had 12 official languages since South African Sign
 * Language was added by the Constitution Eighteenth Amendment Act in July 2023.
 */
export const LANGUAGES: Language[] = [
  {
    code: "zul",
    name: "isiZulu",
    endonym: "isiZulu",
    share: 24.4,
    speakersNote: "Most widely spoken home language in the country",
    regions: ["KZN", "GP", "MP"],
    family: "Nguni (Bantu)",
    blurb:
      "isiZulu is the home language of roughly a quarter of South Africans and is understood far beyond that — it is the default lingua franca of much of Gauteng and KwaZulu-Natal. It carries a deep praise-poetry tradition (izibongo) and a vocabulary of respect that changes depending on who you are speaking to.",
    sound:
      "Three click consonants: c is a dental click (like a 'tsk' of disapproval), q is a palatal click (a cork popping), x is a lateral click (the sound used to urge a horse). The 'hl' in words like hlala is a breathy lateral, not an English 'sh'.",
    greetings: [
      { term: "Sawubona", meaning: "Hello (to one person)", note: "Literally 'I see you'. The reply is Yebo, sawubona." },
      { term: "Sanibonani", meaning: "Hello (to more than one person)" },
      { term: "Unjani?", meaning: "How are you?", note: "Ninjani? to a group." },
      { term: "Ngiyaphila, ngiyabonga", meaning: "I am well, thank you" },
      { term: "Ngiyabonga", meaning: "Thank you" },
      { term: "Hamba kahle", meaning: "Go well", note: "Said to the one leaving." },
      { term: "Sala kahle", meaning: "Stay well", note: "Said by the one leaving." },
    ],
    words: [
      { term: "umuntu / abantu", meaning: "person / people" },
      { term: "ugogo", meaning: "grandmother" },
      { term: "umkhulu", meaning: "grandfather" },
      { term: "umama", meaning: "mother" },
      { term: "ubaba", meaning: "father" },
      { term: "indlu", meaning: "house" },
      { term: "amanzi", meaning: "water" },
      { term: "ukudla", meaning: "food" },
      { term: "ilanga", meaning: "sun / day" },
      { term: "inyanga", meaning: "moon / month / traditional healer" },
      { term: "umlilo", meaning: "fire" },
      { term: "inkomo", meaning: "cow" },
      { term: "umngane", meaning: "friend" },
      { term: "uthando", meaning: "love" },
      { term: "imali", meaning: "money" },
      { term: "isikhathi", meaning: "time" },
    ],
    phrases: [
      { term: "Ngubani igama lakho?", meaning: "What is your name?" },
      { term: "Igama lami ngu…", meaning: "My name is…" },
      { term: "Ngicela usizo", meaning: "I would like to ask for help" },
      { term: "Angizwa kahle", meaning: "I don't hear/understand well" },
      { term: "Uhlala kuphi?", meaning: "Where do you live?" },
      { term: "Ngiyakuthanda", meaning: "I love you" },
      { term: "Kuyabanda namuhla", meaning: "It is cold today" },
      { term: "Ngicela amanzi", meaning: "May I have water please" },
    ],
    proverbs: [
      { text: "Umuntu ngumuntu ngabantu", literal: "A person is a person through other people", meaning: "The idea behind ubuntu: your humanity is made real through how you treat others. You cannot be fully human alone." },
      { text: "Indlela ibuzwa kwabaphambili", literal: "The road is asked from those who have gone ahead", meaning: "Ask the people with experience. Elders and those who have walked the path already are the shortcut." },
      { text: "Isandla sigeza esinye", literal: "One hand washes the other", meaning: "Cooperation. Neither hand can get clean on its own." },
      { text: "Inkunzi isematholeni", literal: "The bull is among the calves", meaning: "Tomorrow's leader is somewhere among today's children — so take young people seriously." },
    ],
    idioms: [
      { text: "Ukubeka itshe esivivaneni", literal: "To place a stone on the cairn", meaning: "To make your contribution to a shared effort. Travellers added a stone to roadside cairns for luck." },
      { text: "Ukudla izambane likapondo", literal: "To eat the pound potato", meaning: "To live very well, to be living the good life." },
      { text: "Akukho qili lazikhotha emhlane", literal: "No clever one ever licked its own back", meaning: "Nobody is so smart that they never need help." },
    ],
    slang: [
      { term: "Heita / Eita", meaning: "Hey, what's up", note: "Standard township greeting across languages." },
      { term: "Sharp sharp / Shap shap", meaning: "All good, agreed, see you" },
      { term: "Ayoba", meaning: "Cool, excellent" },
      { term: "Skhokho", meaning: "A legend, someone who is excellent at what they do" },
      { term: "Sbwl (isibwl)", meaning: "Craving, longing for something", note: "From 'isifiso', written vowel-less online." },
      { term: "Grootman", meaning: "Respected older guy", note: "Afrikaans loan, used in Iscamtho." },
      { term: "Mzansi", meaning: "South Africa", note: "From isiXhosa 'umzantsi', meaning south." },
    ],
  },
  {
    code: "xho",
    name: "isiXhosa",
    endonym: "isiXhosa",
    share: 16.3,
    speakersNote: "Second most spoken home language",
    regions: ["EC", "WC"],
    family: "Nguni (Bantu)",
    blurb:
      "isiXhosa is famous for its clicks — it has fifteen click consonants, more than any other South African official language, absorbed from long contact with Khoe and San languages. It is the language of Nelson Mandela, Thabo Mbeki and a huge body of literature and praise poetry.",
    sound:
      "Clicks come in three places (c dental, q palatal, x lateral) and each can be voiced, aspirated or nasalised — giving fifteen in total. Xhosa also has a 'hl' lateral fricative and tonal distinctions that change meaning.",
    greetings: [
      { term: "Molo", meaning: "Hello (to one person)" },
      { term: "Molweni", meaning: "Hello (to more than one person)" },
      { term: "Unjani?", meaning: "How are you?" },
      { term: "Ndiphilile, enkosi", meaning: "I am well, thank you" },
      { term: "Enkosi", meaning: "Thank you" },
      { term: "Hamba kakuhle", meaning: "Go well" },
      { term: "Sala kakuhle", meaning: "Stay well" },
    ],
    words: [
      { term: "umntu / abantu", meaning: "person / people" },
      { term: "umakhulu", meaning: "grandmother" },
      { term: "utatomkhulu", meaning: "grandfather" },
      { term: "umama", meaning: "mother" },
      { term: "utata", meaning: "father" },
      { term: "indlu", meaning: "house" },
      { term: "amanzi", meaning: "water" },
      { term: "ukutya", meaning: "food" },
      { term: "ilanga", meaning: "sun" },
      { term: "inyanga", meaning: "moon" },
      { term: "umlilo", meaning: "fire" },
      { term: "inkomo", meaning: "cow" },
      { term: "umhlobo", meaning: "friend" },
      { term: "uthando", meaning: "love" },
      { term: "imali", meaning: "money" },
      { term: "ixesha", meaning: "time" },
    ],
    phrases: [
      { term: "Ngubani igama lakho?", meaning: "What is your name?" },
      { term: "Igama lam ngu…", meaning: "My name is…" },
      { term: "Ndicela uncedo", meaning: "I am asking for help" },
      { term: "Andiva", meaning: "I don't understand" },
      { term: "Uhlala phi?", meaning: "Where do you live?" },
      { term: "Ndiyakuthanda", meaning: "I love you" },
      { term: "Uxolo", meaning: "Sorry / excuse me" },
    ],
    proverbs: [
      { text: "Intaka yakha ngoboya benye", literal: "A bird builds its nest with another bird's feathers", meaning: "Nobody builds anything alone — we rely on what others give us." },
      { text: "Umntu ngumntu ngabantu", literal: "A person is a person through other people", meaning: "The isiXhosa form of the ubuntu principle." },
      { text: "Inyathi ibuzwa kwabaphambili", literal: "News of the buffalo is asked of those ahead", meaning: "Consult the people who went before you — they already know what is waiting." },
    ],
    idioms: [
      { text: "Ukuhlala ngeempundu", literal: "To sit on your buttocks", meaning: "To do nothing, to be idle while others work." },
      { text: "Ukuba nentliziyo emhlophe", literal: "To have a white heart", meaning: "To be good-natured and free of malice." },
    ],
    slang: [
      { term: "Awe", meaning: "Hey / what's up", note: "Very common Eastern Cape and Cape Town greeting." },
      { term: "Yhu!", meaning: "Wow / oh no", note: "Exclamation of surprise." },
      { term: "Mfondini", meaning: "My guy, mate" },
      { term: "Ndiyaphambana", meaning: "I'm losing it (with laughter or stress)" },
    ],
  },
  {
    code: "afr",
    name: "Afrikaans",
    endonym: "Afrikaans",
    share: 10.6,
    speakersNote: "Third most spoken home language",
    regions: ["WC", "NC", "EC", "GP"],
    family: "West Germanic, creolised at the Cape",
    blurb:
      "Afrikaans grew at the Cape out of Dutch in the mouths of enslaved people from Southeast Asia and East Africa, Khoi herders, and settlers. The majority of people who speak it as a home language today are coloured South Africans. Some of its earliest written texts were produced in Arabic script in Cape Muslim madrasas in the 1800s — a history that is often left out of the classroom version.",
    sound:
      "The 'g' is a hard throat sound as in 'goed'. 'ui' and 'eu' are rounded vowels with no English equivalent. Double negatives are grammatically required: 'Ek het nie geweet nie.'",
    greetings: [
      { term: "Hallo / Haai", meaning: "Hello" },
      { term: "Goeiemôre", meaning: "Good morning" },
      { term: "Hoe gaan dit?", meaning: "How is it going?" },
      { term: "Dit gaan goed, dankie", meaning: "It's going well, thanks" },
      { term: "Dankie", meaning: "Thank you" },
      { term: "Totsiens", meaning: "Goodbye" },
      { term: "Lekker slaap", meaning: "Sleep well" },
    ],
    words: [
      { term: "mens / mense", meaning: "person / people" },
      { term: "ouma", meaning: "grandmother" },
      { term: "oupa", meaning: "grandfather" },
      { term: "ma", meaning: "mother" },
      { term: "pa", meaning: "father" },
      { term: "huis", meaning: "house" },
      { term: "water", meaning: "water" },
      { term: "kos", meaning: "food" },
      { term: "son", meaning: "sun" },
      { term: "maan", meaning: "moon" },
      { term: "vuur", meaning: "fire" },
      { term: "koei", meaning: "cow" },
      { term: "vriend", meaning: "friend" },
      { term: "liefde", meaning: "love" },
      { term: "geld", meaning: "money" },
      { term: "tyd", meaning: "time" },
    ],
    phrases: [
      { term: "Wat is jou naam?", meaning: "What is your name?" },
      { term: "My naam is…", meaning: "My name is…" },
      { term: "Ek verstaan nie", meaning: "I don't understand" },
      { term: "Waar bly jy?", meaning: "Where do you live?" },
      { term: "Ek is lief vir jou", meaning: "I love you" },
      { term: "Dit is baie lekker", meaning: "That's very nice" },
      { term: "Kom ons braai", meaning: "Let's braai" },
    ],
    proverbs: [
      { text: "'n Boer maak 'n plan", literal: "A farmer makes a plan", meaning: "Make do with what you have. The national attitude to a broken thing." },
      { text: "Al dra 'n aap 'n goue ring, hy is en bly 'n lelike ding", literal: "Even if a monkey wears a gold ring, it is and remains an ugly thing", meaning: "Decoration does not change what something actually is." },
      { text: "Môre is nog 'n dag", literal: "Tomorrow is another day", meaning: "Leave it. It will keep." },
    ],
    idioms: [
      { text: "Die aap uit die mou laat", literal: "To let the monkey out of the sleeve", meaning: "To let the secret out." },
      { text: "Nou gaan die poppe dans", literal: "Now the dolls are going to dance", meaning: "Now there is going to be trouble." },
      { text: "Iemand se kop was", literal: "To wash someone's head", meaning: "To give someone a serious telling-off." },
    ],
    slang: [
      { term: "Lekker", meaning: "Nice, good, tasty, fun", note: "Used by South Africans of every language." },
      { term: "Eish", meaning: "Expression of frustration or sympathy" },
      { term: "Bakkie", meaning: "Pickup truck" },
      { term: "Jol", meaning: "A party, or to party" },
      { term: "Kwaai", meaning: "Cool, great", note: "Literally 'fierce'." },
      { term: "Aweh", meaning: "Hello / agreed", note: "Cape Flats greeting." },
      { term: "Sommer", meaning: "Just because, for no particular reason", note: "Almost untranslatable." },
    ],
  },
  {
    code: "nso",
    name: "Sepedi",
    endonym: "Sepedi / Sesotho sa Leboa",
    share: 10.0,
    speakersNote: "Also known as Northern Sotho",
    regions: ["LP", "GP", "MP"],
    family: "Sotho-Tswana (Bantu)",
    blurb:
      "Sepedi, or Sesotho sa Leboa, is spoken mainly across Limpopo and parts of Gauteng and Mpumalanga. It covers a wide cluster of dialects and has a strong oral tradition of direto (praise poems) and folk tales.",
    sound:
      "Sepedi uses the letters š (like 'sh') and ê / ô for open vowels. It is a tonal language — pitch can change meaning — and words are written disjunctively, so verb parts stand apart.",
    greetings: [
      { term: "Thobela", meaning: "Greetings", note: "Respectful, widely used." },
      { term: "Dumela", meaning: "Hello (to one person)" },
      { term: "Dumelang", meaning: "Hello (to more than one)" },
      { term: "Le kae?", meaning: "How are you? (plural/respectful)" },
      { term: "Re gona", meaning: "We are here / we are fine" },
      { term: "Ke a leboga", meaning: "Thank you" },
      { term: "Sala gabotse", meaning: "Stay well" },
    ],
    words: [
      { term: "motho / batho", meaning: "person / people" },
      { term: "koko", meaning: "grandmother" },
      { term: "rakgolo", meaning: "grandfather" },
      { term: "mma", meaning: "mother" },
      { term: "tate", meaning: "father" },
      { term: "ntlo", meaning: "house" },
      { term: "meetse", meaning: "water" },
      { term: "dijo", meaning: "food" },
      { term: "letšatši", meaning: "sun / day" },
      { term: "kgwedi", meaning: "moon / month" },
      { term: "mollo", meaning: "fire" },
      { term: "kgomo", meaning: "cow" },
      { term: "mogwera", meaning: "friend" },
      { term: "lerato", meaning: "love" },
      { term: "tšhelete", meaning: "money" },
      { term: "nako", meaning: "time" },
    ],
    phrases: [
      { term: "Leina la gago ke mang?", meaning: "What is your name?" },
      { term: "Leina la ka ke…", meaning: "My name is…" },
      { term: "Ga ke kwešiše", meaning: "I don't understand" },
      { term: "O dula kae?", meaning: "Where do you live?" },
      { term: "Ke a go rata", meaning: "I love you" },
    ],
    proverbs: [
      { text: "Tau tša hloka seboka di šitwa ke nare e hlotša", literal: "Lions that fail to work together are defeated by a limping buffalo", meaning: "Without unity, even the strong are beaten by the weak. One of the most quoted proverbs in the country." },
      { text: "Mmago ngwana o swara thipa ka bogaleng", literal: "A child's mother holds the knife by the blade", meaning: "A mother will take the pain herself to protect her child." },
    ],
    idioms: [
      { text: "Go ja mogolo", literal: "To eat the elder", meaning: "To take advantage of someone's seniority or goodwill." },
    ],
    slang: [
      { term: "Sho", meaning: "Hi / ok cool" },
      { term: "Mo fise", meaning: "Let's go hard / turn it up", note: "Sepitori, the Pretoria mix of Sepedi, Setswana and Afrikaans." },
      { term: "Ola", meaning: "Hello", note: "Sepitori." },
    ],
  },
  {
    code: "tsn",
    name: "Setswana",
    endonym: "Setswana",
    share: 8.9,
    speakersNote: "Also the national language of Botswana",
    regions: ["NW", "NC", "GP", "FS"],
    family: "Sotho-Tswana (Bantu)",
    blurb:
      "Setswana is spoken across the North West, the Northern Cape and into Botswana, where it is the national language. It has one of the oldest written records of any Bantu language in southern Africa, with printed material dating back to the early 1800s.",
    sound:
      "Written disjunctively, so a single English word can become several Setswana words. 'Tlh', 'tsh' and 'kg' are single sounds. Tone matters: it distinguishes otherwise identical words.",
    greetings: [
      { term: "Dumela", meaning: "Hello (to one person)" },
      { term: "Dumelang", meaning: "Hello (to more than one)" },
      { term: "O tsogile jang?", meaning: "How did you wake up?" },
      { term: "Ke tsogile sentle", meaning: "I woke up well" },
      { term: "Ke a leboga", meaning: "Thank you" },
      { term: "Tsamaya sentle", meaning: "Go well" },
      { term: "Sala sentle", meaning: "Stay well" },
    ],
    words: [
      { term: "motho / batho", meaning: "person / people" },
      { term: "nkoko", meaning: "grandmother" },
      { term: "rakgolo", meaning: "grandfather" },
      { term: "mme", meaning: "mother" },
      { term: "rre", meaning: "father" },
      { term: "ntlo", meaning: "house" },
      { term: "metsi", meaning: "water" },
      { term: "dijo", meaning: "food" },
      { term: "letsatsi", meaning: "sun / day" },
      { term: "kgwedi", meaning: "moon / month" },
      { term: "molelo", meaning: "fire" },
      { term: "kgomo", meaning: "cow" },
      { term: "tsala", meaning: "friend" },
      { term: "lorato", meaning: "love" },
      { term: "madi", meaning: "money / blood", note: "Context decides which one." },
      { term: "nako", meaning: "time" },
    ],
    phrases: [
      { term: "Leina la gago ke mang?", meaning: "What is your name?" },
      { term: "Leina la me ke…", meaning: "My name is…" },
      { term: "Ga ke tlhaloganye", meaning: "I don't understand" },
      { term: "O nna kae?", meaning: "Where do you stay?" },
      { term: "Ke a go rata", meaning: "I love you" },
    ],
    proverbs: [
      { text: "Mmangwana o tshwara thipa ka fa bogaleng", literal: "A child's mother grabs the knife by the sharp end", meaning: "A mother will endure anything to protect her child." },
      { text: "Kgetsi ya tsie e kgonwa ke go tshwaraganelwa", literal: "A bag of locusts is only manageable when carried together", meaning: "Big burdens become light when shared. Widely used to argue for collective effort." },
      { text: "Motho ke motho ka batho", literal: "A person is a person through people", meaning: "The Setswana form of ubuntu — in Setswana often called botho." },
    ],
    idioms: [
      { text: "Go tshela ka leitlho", literal: "To live by the eye", meaning: "To survive by watching carefully and being alert." },
    ],
    slang: [
      { term: "Ao!", meaning: "Really? / oh no!" },
      { term: "Bathong!", meaning: "Oh people! — surprise or disbelief" },
      { term: "Mfethu", meaning: "My brother, mate" },
    ],
  },
  {
    code: "eng",
    name: "English",
    endonym: "South African English",
    share: 8.7,
    speakersNote: "Dominant in business, media and higher education",
    regions: ["WC", "GP", "KZN", "EC"],
    family: "West Germanic, localised",
    blurb:
      "English is a minority home language in South Africa but carries enormous institutional weight. South African English has absorbed words from Afrikaans, isiZulu, isiXhosa, Khoe languages and Indian languages — and the result is a dialect that other English speakers routinely fail to follow.",
    sound:
      "Non-rhotic, with distinctive 'kit' and 'bath' vowels. The rising intonation at the end of statements is widespread, as is 'hey?' used as a tag question.",
    greetings: [
      { term: "Howzit", meaning: "Hello / how are you", note: "Rarely an actual question." },
      { term: "Hoe gaan dit — 'how's it going'", meaning: "Same thing, Afrikaans origin" },
      { term: "Sharp", meaning: "Hello, goodbye, yes, agreed, fine" },
      { term: "Ja-nee", meaning: "Yes-no — agreement with reservation" },
    ],
    words: [
      { term: "robot", meaning: "traffic light" },
      { term: "bakkie", meaning: "pickup truck" },
      { term: "braai", meaning: "barbecue — and a social institution" },
      { term: "takkies", meaning: "sneakers / trainers" },
      { term: "kombi", meaning: "minibus" },
      { term: "geyser", meaning: "hot water tank" },
      { term: "skinner", meaning: "to gossip" },
      { term: "shame", meaning: "expression of sympathy OR affection", note: "'Shame, he's so cute' is a compliment." },
      { term: "just now", meaning: "soon, maybe, at some point" },
      { term: "now now", meaning: "sooner than just now, but still not now" },
      { term: "boerie", meaning: "boerewors sausage" },
      { term: "spaza", meaning: "informal neighbourhood shop", note: "From isiZulu slang for 'hidden'." },
      { term: "stokvel", meaning: "rotating savings club" },
      { term: "load shedding", meaning: "scheduled rolling power cuts" },
    ],
    phrases: [
      { term: "I'm coming just now", meaning: "I will arrive at an unspecified future time" },
      { term: "Is it?", meaning: "Really? — a general-purpose response" },
      { term: "Ag no man", meaning: "Oh come on" },
      { term: "We'll make a plan", meaning: "We will improvise a solution" },
      { term: "Don't be kwaai with me", meaning: "Don't be harsh with me" },
    ],
    proverbs: [
      { text: "A boer makes a plan", literal: "Direct translation from Afrikaans", meaning: "Used in English with no irony: improvise, fix it with what's here." },
      { text: "Local is lekker", literal: "Local is nice", meaning: "A slogan that became a genuine expression of national preference." },
    ],
    idioms: [
      { text: "To throw your toys out of the cot", literal: "To throw toys out of the cot", meaning: "To have a tantrum." },
      { text: "Now now vs just now", literal: "Two indefinite futures", meaning: "A genuine grammatical feature of SA English: 'now now' is sooner than 'just now', and neither means now." },
    ],
    slang: [
      { term: "Eish", meaning: "Sympathy, frustration, resignation" },
      { term: "Yoh", meaning: "Wow / oh dear" },
      { term: "Chommie", meaning: "Friend" },
      { term: "Jislaaik", meaning: "Expression of amazement" },
      { term: "Sho't left", meaning: "Just around the corner", note: "From taxi directions; became a tourism slogan." },
    ],
  },
  {
    code: "sot",
    name: "Sesotho",
    endonym: "Sesotho",
    share: 7.9,
    speakersNote: "Also the national language of Lesotho",
    regions: ["FS", "GP", "NW"],
    family: "Sotho-Tswana (Bantu)",
    blurb:
      "Sesotho is spoken across the Free State, Gauteng and all of Lesotho. It has an exceptional written literature — Thomas Mofolo's novel Chaka, published in 1925, is one of the great works of African fiction and was written in Sesotho.",
    sound:
      "Uses 'li' where the sound is closer to 'di', and 'ho' at the start of verbs to mark the infinitive. Lesotho and South African spellings differ: 'Sesotho' uses lefatshe, Lesotho uses lefatše.",
    greetings: [
      { term: "Dumela / Lumela", meaning: "Hello" },
      { term: "Dumelang", meaning: "Hello (plural)" },
      { term: "O kae?", meaning: "How are you?" },
      { term: "Ke teng", meaning: "I am here / I am fine" },
      { term: "Kea leboha", meaning: "Thank you" },
      { term: "Tsamaea hantle", meaning: "Go well" },
      { term: "Sala hantle", meaning: "Stay well" },
    ],
    words: [
      { term: "motho / batho", meaning: "person / people" },
      { term: "nkhono", meaning: "grandmother" },
      { term: "ntate-moholo", meaning: "grandfather" },
      { term: "'mè", meaning: "mother" },
      { term: "ntate", meaning: "father" },
      { term: "ntlo", meaning: "house" },
      { term: "metsi", meaning: "water" },
      { term: "lijo", meaning: "food" },
      { term: "letsatsi", meaning: "sun / day" },
      { term: "khoeli", meaning: "moon / month" },
      { term: "mollo", meaning: "fire" },
      { term: "khomo", meaning: "cow" },
      { term: "motsoalle", meaning: "friend" },
      { term: "lerato", meaning: "love" },
      { term: "chelete", meaning: "money" },
      { term: "nako", meaning: "time" },
    ],
    phrases: [
      { term: "Lebitso la hao ke mang?", meaning: "What is your name?" },
      { term: "Lebitso la ka ke…", meaning: "My name is…" },
      { term: "Ha ke utloisise", meaning: "I don't understand" },
      { term: "U lula kae?", meaning: "Where do you live?" },
      { term: "Kea u rata", meaning: "I love you" },
    ],
    proverbs: [
      { text: "Motho ke motho ka batho ba bang", literal: "A person is a person through other people", meaning: "The Sesotho form of ubuntu / botho." },
      { text: "Mphe-mphe e a lapisa, motho o khotše ka sa hae", literal: "Give-me give-me makes one hungry; a person is full from what is their own", meaning: "Living off hand-outs never satisfies. Build something of your own." },
    ],
    idioms: [
      { text: "Ho ja ka meno a ka morao", literal: "To eat with the back teeth", meaning: "To do something secretly or deceitfully." },
    ],
    slang: [
      { term: "Ntwana", meaning: "Young guy, my boy" },
      { term: "Zwakala", meaning: "Come through / pull up" },
      { term: "Haibo!", meaning: "What?! — surprise or objection" },
    ],
  },
  {
    code: "tso",
    name: "Xitsonga",
    endonym: "Xitsonga",
    share: 4.7,
    speakersNote: "Spoken across Limpopo, Mpumalanga and into Mozambique",
    regions: ["LP", "MP", "GP"],
    family: "Tswa-Ronga (Bantu)",
    blurb:
      "Xitsonga is spoken in Limpopo and Mpumalanga and across the border into Mozambique and Zimbabwe. It carries the xibelani dance tradition and a distinctive musical culture, and Tsonga disco and traditional music have had an outsized influence on South African pop.",
    sound:
      "Features 'sw', 'dz', 'hl' and 'rh' clusters. The 'x' is pronounced 'sh', so Xitsonga begins 'shi-'.",
    greetings: [
      { term: "Avuxeni", meaning: "Hello / good morning" },
      { term: "Ku njhani?", meaning: "How are you?" },
      { term: "Ha kona", meaning: "We are here / fine" },
      { term: "Inkomu / Ndza nkhensa", meaning: "Thank you" },
      { term: "Famba kahle", meaning: "Go well" },
      { term: "Sala kahle", meaning: "Stay well" },
    ],
    words: [
      { term: "munhu / vanhu", meaning: "person / people" },
      { term: "kokwana", meaning: "grandparent" },
      { term: "manana", meaning: "mother" },
      { term: "tatana", meaning: "father" },
      { term: "yindlu", meaning: "house" },
      { term: "mati", meaning: "water" },
      { term: "swakudya", meaning: "food" },
      { term: "dyambu", meaning: "sun" },
      { term: "n'weti", meaning: "moon" },
      { term: "ndzilo", meaning: "fire" },
      { term: "homu", meaning: "cow" },
      { term: "munghana", meaning: "friend" },
      { term: "rirhandzu", meaning: "love" },
      { term: "mali", meaning: "money" },
      { term: "nkarhi", meaning: "time" },
    ],
    phrases: [
      { term: "Vito ra wena i mani?", meaning: "What is your name?" },
      { term: "Vito ra mina i…", meaning: "My name is…" },
      { term: "A ndzi twisisi", meaning: "I don't understand" },
      { term: "U tshama kwihi?", meaning: "Where do you live?" },
      { term: "Ndza ku rhandza", meaning: "I love you" },
    ],
    proverbs: [
      { text: "N'wana wa mfenhe a nga tsandzeki hi rhavi", literal: "A baboon's child does not fail to grab a branch", meaning: "Children inherit the abilities of their parents — it is in the blood." },
      { text: "Vukosi a byi peli nambu", literal: "Chieftainship does not cross the river", meaning: "Authority has limits; it does not apply outside its own territory." },
    ],
    idioms: [
      { text: "Ku dya hi mavoko mambirhi", literal: "To eat with both hands", meaning: "To take greedily, to benefit from two sides at once." },
    ],
    slang: [
      { term: "Mjolo", meaning: "Dating / relationships", note: "Now used nationwide online." },
      { term: "Xibelani", meaning: "The dance and the skirt worn for it" },
    ],
  },
  {
    code: "ssw",
    name: "siSwati",
    endonym: "siSwati",
    share: 2.9,
    speakersNote: "Also the language of Eswatini",
    regions: ["MP"],
    family: "Nguni (Bantu)",
    blurb:
      "siSwati is spoken mainly in Mpumalanga and across the border in Eswatini. It is closely related to isiZulu but is immediately recognisable by its distinctive spelling and sound shifts — 'tf' and 'dv' where isiZulu has 'th' and 'b'.",
    sound:
      "Where isiZulu writes 'umuntu', siSwati writes 'umuntfu'. 'dv' is a soft 'd' with lip rounding. The language has the same three clicks as isiZulu but uses them less often.",
    greetings: [
      { term: "Sawubona", meaning: "Hello (to one person)" },
      { term: "Sanibonani", meaning: "Hello (to more than one)" },
      { term: "Unjani?", meaning: "How are you?" },
      { term: "Ngiyaphila", meaning: "I am well" },
      { term: "Ngiyabonga", meaning: "Thank you" },
      { term: "Hamba kahle", meaning: "Go well" },
    ],
    words: [
      { term: "umuntfu / bantfu", meaning: "person / people" },
      { term: "gogo", meaning: "grandmother" },
      { term: "mkhulu", meaning: "grandfather" },
      { term: "make", meaning: "mother" },
      { term: "babe", meaning: "father" },
      { term: "indlu", meaning: "house" },
      { term: "emanti", meaning: "water" },
      { term: "kudla", meaning: "food" },
      { term: "lilanga", meaning: "sun" },
      { term: "inyanga", meaning: "moon" },
      { term: "umlilo", meaning: "fire" },
      { term: "inkhomo", meaning: "cow" },
      { term: "umngani", meaning: "friend" },
      { term: "lutsandvo", meaning: "love" },
      { term: "imali", meaning: "money" },
      { term: "sikhatsi", meaning: "time" },
    ],
    phrases: [
      { term: "Ungubani libito lakho?", meaning: "What is your name?" },
      { term: "Libito lami ngu…", meaning: "My name is…" },
      { term: "Angiva", meaning: "I don't understand" },
      { term: "Uhlala kuphi?", meaning: "Where do you live?" },
      { term: "Ngiyakutsandza", meaning: "I love you" },
    ],
    proverbs: [
      { text: "Umuntfu ngumuntfu ngebantfu", literal: "A person is a person through other people", meaning: "The siSwati form of ubuntu." },
      { text: "Inyoni yakha ngelusiba lwenye", literal: "A bird builds with another's feather", meaning: "We build our lives out of what others contribute." },
    ],
    idioms: [
      { text: "Kudla imali", literal: "To eat money", meaning: "To waste or misappropriate funds." },
    ],
    slang: [{ term: "Yebo", meaning: "Yes" }, { term: "Cha", meaning: "No" }],
  },
  {
    code: "ven",
    name: "Tshivenda",
    endonym: "Tshivenḓa",
    share: 2.5,
    speakersNote: "Concentrated in northern Limpopo",
    regions: ["LP"],
    family: "Venda (Bantu) — relatively isolated",
    blurb:
      "Tshivenda sits slightly apart from South Africa's other Bantu languages, with links northward towards Shona. Venda culture carries the domba python dance, sacred sites such as Lake Fundudzi, and a famously formal system of greeting.",
    sound:
      "Written with underdotted consonants — ḓ, ṱ, ṋ, ḽ — which mark dental articulation and genuinely change meaning. Tshivenda is tonal.",
    greetings: [
      { term: "Ndaa!", meaning: "Greeting spoken by men", note: "Men and women use different greeting words — this is strict etiquette." },
      { term: "Aa!", meaning: "Greeting spoken by women" },
      { term: "Vho vuwa hani?", meaning: "How did you wake?" },
      { term: "Ndo vuwa, ndo takala", meaning: "I woke well, I am happy" },
      { term: "Ndo livhuwa", meaning: "Thank you" },
      { term: "Kha vha sale zwavhuḓi", meaning: "Stay well" },
    ],
    words: [
      { term: "muthu / vhathu", meaning: "person / people" },
      { term: "makhulu", meaning: "grandmother / grandparent" },
      { term: "mme", meaning: "mother" },
      { term: "khotsi", meaning: "father" },
      { term: "nnḓu", meaning: "house" },
      { term: "maḓi", meaning: "water" },
      { term: "zwiḽiwa", meaning: "food" },
      { term: "ḓuvha", meaning: "sun / day" },
      { term: "ṅwedzi", meaning: "moon / month" },
      { term: "mulilo", meaning: "fire" },
      { term: "kholomo", meaning: "cow" },
      { term: "khonani", meaning: "friend" },
      { term: "lufuno", meaning: "love" },
      { term: "tshelede", meaning: "money" },
      { term: "tshifhinga", meaning: "time" },
    ],
    phrases: [
      { term: "Dzina ḽaṋu ndi nnyi?", meaning: "What is your name?" },
      { term: "Dzina ḽanga ndi…", meaning: "My name is…" },
      { term: "A thi pfesesi", meaning: "I don't understand" },
      { term: "Ni dzula ngafhi?", meaning: "Where do you live?" },
      { term: "Ndi a ni funa", meaning: "I love you" },
    ],
    proverbs: [
      { text: "Muthu ndi muthu nga vhaṅwe", literal: "A person is a person through others", meaning: "The Tshivenda expression of ubuntu." },
    ],
    idioms: [
      { text: "Ndaa and Aa", literal: "The gendered greeting", meaning: "Not an idiom but a rule: using the wrong greeting word for your gender marks you immediately as an outsider. Greeting correctly is the first test of respect." },
    ],
    slang: [{ term: "Vho-", meaning: "Respectful title placed before an elder's name" }],
  },
  {
    code: "nbl",
    name: "isiNdebele",
    endonym: "isiNdebele",
    share: 1.6,
    speakersNote: "Smallest of the eleven spoken official languages",
    regions: ["MP", "GP", "LP"],
    family: "Nguni (Bantu)",
    blurb:
      "Southern Ndebele is spoken mainly in Mpumalanga and parts of Gauteng and Limpopo. Ndebele visual culture is globally recognised: the bold geometric house painting developed by Ndebele women, carried into international art by Esther Mahlangu, who has painted everything from BMW art cars to gallery walls.",
    sound:
      "Nguni, so it shares the clicks with isiZulu and isiXhosa, but with distinct vocabulary — 'Lotjhani' rather than 'Sawubona'. The 'tjh' is a sharp 'ch'.",
    greetings: [
      { term: "Lotjhani", meaning: "Hello" },
      { term: "Unjani?", meaning: "How are you?" },
      { term: "Ngikhona", meaning: "I am here / well" },
      { term: "Ngiyathokoza", meaning: "Thank you" },
      { term: "Khamba kuhle", meaning: "Go well" },
      { term: "Sala kuhle", meaning: "Stay well" },
    ],
    words: [
      { term: "umuntu / abantu", meaning: "person / people" },
      { term: "ugogo", meaning: "grandmother" },
      { term: "ubabamkhulu", meaning: "grandfather" },
      { term: "umma", meaning: "mother" },
      { term: "ubaba", meaning: "father" },
      { term: "indlu", meaning: "house" },
      { term: "amanzi", meaning: "water" },
      { term: "ukudla", meaning: "food" },
      { term: "ilanga", meaning: "sun" },
      { term: "inyezi", meaning: "moon" },
      { term: "umlilo", meaning: "fire" },
      { term: "ikomo", meaning: "cow" },
      { term: "umngani", meaning: "friend" },
      { term: "ithando", meaning: "love" },
      { term: "imali", meaning: "money" },
    ],
    phrases: [
      { term: "Ngubani ibizo lakho?", meaning: "What is your name?" },
      { term: "Ibizo lami ngu…", meaning: "My name is…" },
      { term: "Angizwisisi", meaning: "I don't understand" },
      { term: "Uhlala kuphi?", meaning: "Where do you live?" },
    ],
    proverbs: [
      { text: "Umuntu ngumuntu ngabantu", literal: "A person is a person through other people", meaning: "Ubuntu, in isiNdebele." },
    ],
    idioms: [
      { text: "Ukupenda indlu", literal: "To paint the house", meaning: "In Ndebele tradition, repainting the homestead marks a change in the family — a marriage, an initiation, a return. The wall is a public announcement." },
    ],
    slang: [{ term: "Yoh", meaning: "Wow" }],
  },
  {
    code: "sasl",
    name: "South African Sign Language",
    endonym: "SASL",
    share: 0.02,
    speakersNote: "Became the 12th official language in July 2023",
    regions: ["NAT"],
    family: "Signed language — its own grammar, not signed English",
    blurb:
      "South African Sign Language became South Africa's twelfth official language when the Constitution Eighteenth Amendment Act was signed into law in July 2023. SASL is a full natural language with its own grammar, spatial syntax and regional variation — it is not English rendered on the hands, and it is not a universal sign language.",
    sound:
      "Meaning is carried by handshape, location, movement, palm orientation and — critically — non-manual features: eyebrows, mouth and head position. Raised eyebrows mark a yes/no question; furrowed brows mark a wh-question.",
    greetings: [
      { term: "HELLO", meaning: "Flat hand raised from the forehead outward, like a relaxed salute" },
      { term: "HOW ARE YOU", meaning: "Curved hands turning upward at the chest, with a questioning facial expression" },
      { term: "THANK YOU", meaning: "Flat hand moving forward and down from the chin" },
      { term: "NICE TO MEET YOU", meaning: "Index fingers brought together in front of the body" },
    ],
    words: [
      { term: "NAME", meaning: "Two fingers of each hand tapped together twice" },
      { term: "DEAF", meaning: "Index finger touching the ear then the mouth" },
      { term: "MOTHER", meaning: "Regional variation is common — several signs are in use across the country" },
      { term: "SCHOOL", meaning: "Flat hands clapped together twice" },
      { term: "SOUTH AFRICA", meaning: "A sign tracing the shape of the country" },
    ],
    phrases: [
      { term: "Eyebrow position", meaning: "Raised = yes/no question. Lowered = who/what/where question. The hands alone are not enough." },
      { term: "Topic–comment order", meaning: "SASL typically sets the topic first, then comments on it — a different word order from English." },
      { term: "Fingerspelling", meaning: "A one-handed manual alphabet is used mainly for names and loan words." },
    ],
    proverbs: [
      { text: "Nothing About Us Without Us", literal: "Deaf community organising slogan", meaning: "The principle behind the campaign that won SASL official status: Deaf South Africans must lead decisions about Deaf life." },
    ],
    idioms: [
      { text: "SASL is not universal", literal: "Sign languages are not international", meaning: "SASL differs from American and British sign languages, and there is real regional variation within South Africa, partly a legacy of segregated Deaf schools." },
    ],
    slang: [{ term: "Name signs", meaning: "Deaf communities give each person a personal sign, usually based on a physical trait or habit. You do not choose your own." }],
  },
];

export const LANGUAGE_BY_CODE = Object.fromEntries(LANGUAGES.map((l) => [l.code, l]));
