import type { Story } from "@/lib/types";

/**
 * IMPORTANT — these are illustrative seed entries, written to show the shape of the
 * archive before real community recordings exist. Every one is flagged `seeded: true`
 * and is labelled in the UI, so it can never be mistaken for a genuine oral-history
 * testimony. Historical context inside them (dates, places, events) is real.
 */
export const STORIES: Story[] = [
  {
    slug: "how-we-used-to-get-married",
    title: "How we used to get married",
    kind: "gogo",
    teller: "Gogo Nomusa",
    tellerRole: "Grandmother, 78",
    place: "Nquthu",
    province: "KZN",
    year: "Remembering the 1960s",
    minutes: 7,
    summary:
      "Lobola negotiations that lasted four months, a bride who was not allowed to smile, and the umabo ceremony where the family you married into finally became yours.",
    body: [
      "Nobody asked me if I wanted to get married. That is not how it was. My uncle came to the house and said the Mkhize family had sent people, and I must behave myself.",
      "The negotiation did not happen in a day. The delegation from his family came and sat outside the gate — they do not just walk in. They sent a message with a small amount of money to be allowed to speak. Then the talking started, and it went on for four months. Back and forth. Eleven cattle in the end, and they paid in instalments, because who has eleven cattle at once?",
      "What people today do not understand is that lobola was never buying a person. It was two families binding themselves together so that they could not easily walk away from each other. If I had trouble in that house, my family had standing to come and ask questions. The cattle were the proof of that standing.",
      "At umabo I brought my gifts — blankets, grass mats, pots — and I gave them to each person in his family by name. You must know every name. His mother's sisters, the children, everyone. That was how you were shown to be entering the family properly, not just arriving.",
      "I was not allowed to smile. For the whole ceremony. A bride who smiles too much is said to be too eager to leave her own home, and that shames her mother. So I kept my eyes down and my face still, and inside I was thinking about whether the man could actually farm.",
      "Now I watch these weddings on the phone, with the white dress in the morning and the traditional clothes in the afternoon, and everybody dancing and filming. I am not against it. But I ask them: do you know the names? Can you greet everybody in that family properly? Because that is the part that was the marriage. The rest was just the party.",
    ],
    pullQuote: "Lobola was never buying a person. It was two families binding themselves so they could not easily walk away from each other.",
    language: "isiZulu, translated",
    tags: ["lobola", "umabo", "marriage", "KwaZulu-Natal"],
    seeded: true,
  },
  {
    slug: "night-the-lights-came",
    title: "The night the lights came to the village",
    kind: "mkhulu",
    teller: "Mkhulu Tshilidzi",
    tellerRole: "Grandfather, 81",
    place: "Near Thohoyandou",
    province: "LP",
    year: "Remembering the 1990s",
    minutes: 6,
    summary:
      "Electrification arrived late in this part of Venda. An old man remembers the night the poles were switched on, and what the village lost along with the dark.",
    body: [
      "The poles stood there for nearly a year before anything came out of them. Children used to knock on them to hear the sound. We stopped believing they would work.",
      "Then one evening in winter they came on. Not all at once — you would see one house, then another, then the whole row. People went outside to look at their own houses. I remember my wife standing in the doorway with the light behind her and I could not see her face properly, only the shape.",
      "The first thing that changed was the fire. We used to sit around the fire every night, all of us, and that is where you heard everything — who was sick, who was pregnant, what happened at the chief's place, and the old stories. The fire was the reason we sat together. Once there was a light in the house, people went inside.",
      "Then the television came, and after that nobody told stories at all. I am not saying the electricity was bad. My grandchildren study at night. We have a fridge. Nobody walks to the clinic in the dark with a paraffin lamp anymore.",
      "But I want somebody to write down that there was a cost. We swapped the fire for the light, and the stories went with the fire. That is why I am sitting here talking into this phone. If nobody tells it, then in twenty years it will be as if that village never existed in the dark at all.",
    ],
    pullQuote: "We swapped the fire for the light, and the stories went with the fire.",
    language: "Tshivenda, translated",
    tags: ["electrification", "village life", "Limpopo", "storytelling"],
    seeded: true,
  },
  {
    slug: "sophiatown-before-the-trucks",
    title: "Sophiatown, before the trucks came",
    kind: "township",
    teller: "Ntate Sechaba",
    tellerRole: "Community historian, 86",
    place: "Sophiatown, Johannesburg",
    province: "GP",
    year: "Remembering 1955",
    minutes: 9,
    summary:
      "On 9 February 1955 government trucks and armed police began removing the residents of Sophiatown to Meadowlands. A man who was a boy at the time remembers the week before.",
    body: [
      "You have to understand what Sophiatown was. It was one of the very few places where Black people could own the freehold title to land in Johannesburg. My father had a deed. A piece of paper with his name on it. That is why the place was dangerous to them.",
      "It was mixed. Black, coloured, Indian, Chinese, a few white people. Shebeens, jazz, three cinemas, gangsters in good suits. Father Trevor Huddleston was at the church there. Hugh Masekela got his first trumpet through him. Miriam Makeba sang in that place as a young woman. Can you imagine that concentration of people in a few streets?",
      "We knew it was coming. The Natives Resettlement Act had been passed. There were meetings — the slogan was Ons dak nie, ons phola hier. We are not moving, we are staying here. People really believed it could be stopped.",
      "They came early, on the ninth of February, and they came before the date everyone expected, so the organising could not hold. Trucks, and police with guns. They did not ask. They loaded the furniture and the people and drove to Meadowlands, out in the veld, where there was nothing. Numbered houses in rows.",
      "Then they knocked Sophiatown down and built a white suburb on it and they called it Triomf. Triumph. They actually named it that.",
      "The thing nobody records properly is what it did to the music. In Sophiatown everybody lived close enough to hear each other practise. In Meadowlands they spread us out on purpose. You cannot make that sound again once the streets are gone.",
      "The name was changed back to Sophiatown in 2006. I was there. But a name coming back is not the same as a place coming back.",
    ],
    pullQuote: "They knocked it down, built a white suburb on it, and called it Triomf. Triumph. They actually named it that.",
    language: "English",
    tags: ["forced removals", "Sophiatown", "1955", "Johannesburg", "jazz"],
    audio: ["/audio/sophiatown-1.mp3", "/audio/sophiatown-2.mp3"],
    seeded: true,
  },
  {
    slug: "hanover-street-smell",
    title: "District Six: what Hanover Street smelled like",
    kind: "township",
    teller: "Auntie Galiema",
    tellerRole: "Former resident, 74",
    place: "District Six, Cape Town",
    province: "WC",
    year: "Remembering 1966–1976",
    minutes: 8,
    summary:
      "District Six was declared a white area on 11 February 1966. Around 60,000 people were moved to the Cape Flats. A woman remembers the street, the food and the day the bulldozers reached her road.",
    body: [
      "People always ask what District Six looked like. I remember what it smelled like. Hanover Street in the morning: koesisters frying, fish from the barrows, the spice shop, coal smoke, and the sea somewhere underneath all of it.",
      "On a Sunday morning you could not walk fast on that street because you had to greet everybody. Muslim, Christian, Jewish, it did not matter. The Moravian church bells and the call to prayer in the same air.",
      "They declared it a white group area in 1966. For years nothing happened, and we thought maybe. Then the demolitions started and they just worked through it, street by street, for years. About sixty thousand people removed. They put us out on the Cape Flats — Hanover Park, Mitchells Plain, Manenberg — far from work, far from each other, with the wind and the sand.",
      "What they broke was not only the houses. In District Six I knew who my children were with at any hour because the whole street watched them. On the Flats nobody knew anybody. They mixed up the families on purpose so the old streets could not reform. The gangs came into that gap. I will say that to anybody.",
      "And here is the thing that still makes me angry: they bulldozed it and then they could not build on it. Most of it lay empty for decades. Grass and rubble and the church steeples left standing, because they did not dare knock down the churches and the mosques.",
      "There is a museum there now in the old Methodist church, with the street signs that somebody saved and a big map on the floor where ex-residents write their own house onto it. I wrote mine. That is the only address I ever really had.",
    ],
    pullQuote: "They bulldozed it and then could not build on it. It lay empty for decades, with the church steeples still standing.",
    language: "Afrikaans and English",
    tags: ["District Six", "forced removals", "Cape Town", "1966"],
    seeded: true,
  },
  {
    slug: "water-before-school",
    title: "We fetched water before school",
    kind: "childhood",
    teller: "Mama Nosipho",
    tellerRole: "Retired teacher, 63",
    place: "Near Mthatha",
    province: "EC",
    year: "Remembering the 1970s",
    minutes: 5,
    summary:
      "Two trips to the river before the school bell, a twenty-litre tin carried on the head, and the games that happened on the path because the path was the only free time anyone had.",
    body: [
      "The alarm clock was my grandmother's voice. Before five. You go to the river, you come back, you go again, and then you wash and you walk to school. Two trips, every morning, and more in the afternoon.",
      "The tin was twenty litres. You put a cloth ring on your head first — the inkatha — and the tin sits on that. Once it is up there you cannot look down and you cannot stop walking properly, so you learn to walk with your whole spine straight. Teachers used to say you could tell which girls fetched water by how they stood.",
      "The path was where everything happened. That was our only unsupervised time in the whole day. We played on the path. We sang, we argued, we told each other the news. Somebody always knew something.",
      "In the dry season the river went down and you had to scoop from a hole in the sand and wait for it to clear. You would sit there in the dark waiting for clean water and that was also time to talk.",
      "I became a teacher and I taught in that same district for thirty-one years. There are taps now in most of those homesteads. Good. I do not want any child carrying twenty litres on their head before school.",
      "But I will tell you what nobody planned for. Those children now have no path. No hour in the day that belongs only to them, where the adults are not there and the phone is not there. We complained about the walk every single day. It was also the best part of the day.",
    ],
    pullQuote: "We complained about that walk every single day. It was also the best part of the day.",
    language: "isiXhosa, translated",
    tags: ["childhood", "water", "Eastern Cape", "school"],
    audio: ["/audio/water-1.mp3", "/audio/water-2.mp3"],
    seeded: true,
  },
  {
    slug: "three-legged-pot",
    title: "How we used to live: the three-legged pot",
    kind: "howwelived",
    teller: "Koko Mmapula",
    tellerRole: "Grandmother, 80",
    place: "Ga-Sekhukhune",
    province: "LP",
    year: "Remembering the 1950s–60s",
    minutes: 6,
    summary:
      "Before gas and electricity: how a household ran on one cast-iron pot, a daily fire, and a set of rules about who ate from which dish.",
    body: [
      "One pot. Three legs so it stands in the fire by itself, no stove needed. Everything came out of that pot — the morning porridge, the beans, the meat on the days there was meat.",
      "You never washed it with soap. You scraped it and wiped it and kept it black. A new pot had to be seasoned with fat until it stopped sticking, and after that it only got better. My mother's pot went to my sister and it is still cooking.",
      "The fire was the work. You collect the wood in the afternoon, you bank the coals at night, and in the morning you blow the coals back to life so you do not waste a match. A child who could restart the fire from last night's coals was a useful child.",
      "There were rules about eating that nobody wrote down. Men and boys ate from one dish, women and girls from another. The oldest reached first. You ate with your right hand. You did not speak at the beginning of the meal. If a visitor arrived while food was on the fire, the food was already theirs, even if it meant the family ate less — that was absolute.",
      "Maize meal was the centre of everything. Pap in the morning, pap at night, with morogo picked from around the fields, and sour milk when there was milk. People think that was poverty food. Some of it was. But we also did not throw anything away and nobody in that village had the diseases people have now.",
      "If you want to cook properly in a three-legged pot, you must learn the coals, not the recipe. Move the coals, not the pot.",
    ],
    pullQuote: "If you want to cook in a three-legged pot, learn the coals, not the recipe. Move the coals, not the pot.",
    language: "Sepedi, translated",
    tags: ["how we used to live", "cooking", "Limpopo", "potjie"],
    seeded: true,
  },
  {
    slug: "lake-you-do-not-point-at",
    title: "The lake you are not allowed to point at",
    kind: "village",
    teller: "Vho-Masindi",
    tellerRole: "Elder, 69",
    place: "Lake Fundudzi, Venda",
    province: "LP",
    year: "Ongoing tradition",
    minutes: 5,
    summary:
      "Lake Fundudzi is a sacred site held by the Netshiavha clan. An elder explains the protocols: why you greet the lake upside down, and why you do not simply drive there.",
    body: [
      "Fundudzi is not a tourist attraction. I want to start there, because people arrive with cameras and they are surprised when they are turned around.",
      "The lake sits below the Thathe Vondo forest. It was formed when a landslide blocked the Mutale River, so it has an inflow and no visible outflow, which is part of why it has always been regarded as unusual. The land and the custodianship belong to the Netshiavha people. You do not go without permission from the custodians.",
      "The greeting is the part everybody hears about. You do not face the lake and greet it directly. You turn your back, bend forward, and look at the water from between your legs — so you are seeing it upside down. That is ukodola. It is a sign that you are not approaching as an equal.",
      "There are things that are not spoken about to outsiders, and I am not going to put them on a phone. There is a python associated with the lake, and there is an annual rite. That is as far as I will go, and anybody who tells you more for money is selling you something that is not theirs.",
      "Why does this matter to a young person in Johannesburg? Because this is one of the places where the protocol is still intact. Most sacred sites in this country were broken, fenced, renamed or drowned. This one still has rules that are actually followed. That is rare and it is worth more than the photograph.",
      "If you want to come: ask. Go through the custodians, not through a tour company. And when you get there, do the greeting properly. People are watching, and they will tell you if you did it wrong.",
    ],
    pullQuote: "You turn your back and look at the water from between your legs. You are not approaching as an equal.",
    language: "Tshivenda, translated",
    tags: ["sacred sites", "Venda", "Fundudzi", "protocol"],
    audio: ["/audio/fundudzi-1.mp3", "/audio/fundudzi-2.mp3"],
    seeded: true,
  },
  {
    slug: "how-our-mothers-banked",
    title: "Stokvel: how our mothers banked",
    kind: "howwelived",
    teller: "Mam' Dudu",
    tellerRole: "Stokvel treasurer, 67",
    place: "Soweto",
    province: "GP",
    year: "From the 1970s to now",
    minutes: 6,
    summary:
      "Locked out of banks, women built their own rotating credit system — with rules, minutes, fines and a strongbox. Stokvels still move billions of rands a year.",
    body: [
      "The banks did not want us. Not really. So we made our own.",
      "It is simple. Twelve women, each pays in the same amount every month, and each month the whole pot goes to one member. By the end of the year everybody has had a turn with a lump sum they could never have saved alone. That is a stokvel.",
      "But do not think it was casual. We had a constitution. Written down. Fines if you came late to the meeting. Fines if your money was short. Two signatures on the box. Minutes taken every month in an exercise book. I still have the books from 1984.",
      "The real thing it did was not financial. It was that twelve women had to meet every month, in each other's houses, in rotation. So you saw the inside of everybody's home. You knew if somebody's child was not at school, if somebody's husband was a problem, if there was no food in that kitchen. And the group would quietly do something about it.",
      "There are burial stokvels, grocery stokvels, December stokvels where you buy the whole Christmas in bulk, and investment stokvels that own property now. Surveys put the amount of money moving through stokvels in South Africa in the tens of billions of rands each year. Millions of people are in them.",
      "The young ones do it on their phones now with a group chat and instant transfers. Fine. But keep the meeting. The money was never the main thing. The meeting was the main thing.",
    ],
    pullQuote: "The money was never the main thing. The meeting was the main thing.",
    language: "isiZulu and English",
    tags: ["stokvel", "Soweto", "money", "women"],
    seeded: true,
  },
  {
    slug: "herding-and-the-veld",
    title: "What herd boys actually did all day",
    kind: "childhood",
    teller: "Ntate Molefe",
    tellerRole: "Farmer, 71",
    place: "Near Ficksburg",
    province: "FS",
    year: "Remembering the 1960s",
    minutes: 6,
    summary:
      "Herding was not idle time. It was an unsupervised school where boys learned tracking, weather, stick fighting, clay sculpture and the entire morabaraba opening book.",
    body: [
      "People hear 'herd boy' and they picture a child sitting on a rock doing nothing. We were running an operation.",
      "You are responsible for animals worth more than everything in your family's house. You have to know every animal by face. You have to know which cow is about to calve, which one breaks fences, where the poisonous plants grow, and which dongas will trap an animal in the rain.",
      "You read weather all day. Not from a phone. From the way the cattle lie down, from the ants, from the colour of the horizon in the afternoon. If you brought the herd home late because you misread a storm, that was a serious failure.",
      "And in between, that was where we learned everything else. We scratched morabaraba boards in the dust and played all day. I can still see those boards. We fought with sticks, properly, with rules, and the older boys refereed. We made cattle out of clay and left them in the sun to dry — every boy had a clay herd, and your clay herd was a statement about the herd you intended to own.",
      "No adults. That is the point people miss. For eight hours a day you were in a society of children, governed by children, with real consequences. You learned to argue a case. You learned what happens if you lie about something that can be checked.",
      "My grandson has a tutor, a tablet and a lift to school. He is better educated than I was. But if I put him in that veld at six in the morning with forty cattle, he would lose them by nine.",
    ],
    pullQuote: "For eight hours a day you were in a society of children, governed by children, with real consequences.",
    language: "Sesotho, translated",
    tags: ["herding", "childhood", "Free State", "morabaraba"],
    seeded: true,
  },
  {
    slug: "what-he-would-not-tell-me",
    title: "Initiation: what my grandfather would and would not tell me",
    kind: "mkhulu",
    teller: "Anonymous contributor",
    tellerRole: "Submitted with the family's permission",
    place: "Eastern Cape",
    province: "EC",
    year: "Recorded recently",
    minutes: 4,
    summary:
      "A grandson records what an elder is willing to say publicly about ulwaluko — and documents the boundary itself, because the boundary is part of the knowledge.",
    body: [
      "I asked my grandfather to record his initiation for this archive. He said yes, and then he said: you will record what I decide to say, and you will not ask me for more. So this entry is partly about the limit.",
      "What he would say: that ulwaluko is a passage into manhood, that it involves seclusion, instruction from elders, and a return to the community as a different person with different obligations. That the instruction is mostly about responsibility — towards your family, your wife, your neighbours and the people below you.",
      "That the hardest part was not the physical part. It was the silence and the waiting, and being told that the boy you were is now finished and is not coming back.",
      "That coming home is a public event. The community has to receive you. You are given new clothes and often a new way of being addressed. People who knew you your whole life treat you differently from that morning onwards, and you have to live up to it immediately.",
      "What he would not say: the specifics of the teaching, anything that happens inside the seclusion, the songs, and the names. He said those things only work if they arrive in the right order from the right person. Writing them down takes the order away.",
      "He also said something I want on the record. He said that too many boys are dying now, in illegal schools run by people with no standing, and that this is not tradition — it is the collapse of tradition, because the people who were supposed to be accountable are not. He said: write that part down. Write that the elders are angry.",
    ],
    pullQuote: "Those things only work if they arrive in the right order from the right person. Writing them down takes the order away.",
    language: "isiXhosa and English",
    tags: ["ulwaluko", "initiation", "Eastern Cape", "protocol"],
    seeded: true,
  },
];

export const STORY_BY_SLUG = Object.fromEntries(STORIES.map((s) => [s.slug, s]));

export const STORY_KINDS: { id: Story["kind"]; label: string; emoji: string }[] = [
  { id: "gogo", label: "Gogo stories", emoji: "👵🏾" },
  { id: "mkhulu", label: "Mkhulu stories", emoji: "👴🏾" },
  { id: "childhood", label: "Childhood memories", emoji: "🧒🏾" },
  { id: "village", label: "Village history", emoji: "🏞️" },
  { id: "township", label: "Township history", emoji: "🏘️" },
  { id: "howwelived", label: "How we used to live", emoji: "🔥" },
];
