/**
 * Builds src/content/za-map.ts — an offline, tile-free SVG basemap of South Africa.
 *
 * Source geometry: Highcharts map-collection "za-all" (built on public-domain Natural Earth
 * data). Its coordinates sit in an equidistant-cylindrical grid with a north-up Y axis.
 * We recover the exact lng/lat -> grid transform from the four unambiguous national extreme
 * points, then flip Y into screen space so everything downstream is plain SVG coordinates.
 *
 *   westernmost  Alexander Bay   16.4507E   -> x -999
 *   easternmost  Kosi Bay        32.8860E   -> x 9851
 *   northernmost Limpopo tip    -22.1250S   -> y 9851 (pre-flip)
 *   southernmost Cape Agulhas   -34.8333S   -> y  295 (pre-flip)
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const geo = JSON.parse(fs.readFileSync(path.join(__dirname, "za-provinces.geo.json"), "utf8"));

const AX = (9851 - -999) / (32.886 - 16.4507);
const BX = -999 - AX * 16.4507;
const AY = (9851 - 295) / (-22.125 - -34.8333);
const BY = 295 - AY * -34.8333;
const FLIP = 295 + 9851; // screenY = FLIP - gridY

const NAME_FIX = { "Orange Free State": "Free State" };
const CODE = { "za-ec": "EC", "za-np": "LP", "za-nl": "KZN", "za-wc": "WC", "za-nc": "NC", "za-nw": "NW", "za-fs": "FS", "za-gt": "GP", "za-mp": "MP" };
const ABBR = { EC: "Eastern Cape", LP: "Limpopo", KZN: "KwaZulu-Natal", WC: "Western Cape", NC: "Northern Cape", NW: "North West", FS: "Free State", GP: "Gauteng", MP: "Mpumalanga" };

const ringsOf = (f) => {
  const rs = f.geometry.type === "Polygon" ? [f.geometry.coordinates] : f.geometry.coordinates;
  return rs;
};
const inRing = (p, r) => {
  let c = false;
  for (let i = 0, j = r.length - 1; i < r.length; j = i++) {
    const [xi, yi] = r[i], [xj, yj] = r[j];
    if ((yi > p[1]) !== (yj > p[1]) && p[0] < ((xj - xi) * (p[1] - yi)) / (yj - yi) + xi) c = !c;
  }
  return c;
};
const segDist = (p, a, b) => {
  const vx = b[0] - a[0], vy = b[1] - a[1], wx = p[0] - a[0], wy = p[1] - a[1];
  const L = vx * vx + vy * vy;
  const t = Math.max(0, Math.min(1, L ? (wx * vx + wy * vy) / L : 0));
  return Math.hypot(p[0] - (a[0] + t * vx), p[1] - (a[1] + t * vy));
};
/** Pole of inaccessibility (coarse grid search) — far better label anchors than a centroid. */
function labelPoint(polys) {
  let minX = Infinity, minY = Infinity, maxX = -Infinity, maxY = -Infinity;
  let big = null, bigArea = 0;
  for (const poly of polys) {
    const r = poly[0];
    let a = 0;
    for (let i = 0; i < r.length; i++) { const [x1, y1] = r[i], [x2, y2] = r[(i + 1) % r.length]; a += x1 * y2 - x2 * y1; }
    if (Math.abs(a) > Math.abs(bigArea)) { bigArea = a; big = poly; }
  }
  for (const [x, y] of big[0]) { minX = Math.min(minX, x); maxX = Math.max(maxX, x); minY = Math.min(minY, y); maxY = Math.max(maxY, y); }
  let best = null, bestD = -1;
  const N = 48;
  for (let i = 1; i < N; i++) for (let j = 1; j < N; j++) {
    const p = [minX + ((maxX - minX) * i) / N, minY + ((maxY - minY) * j) / N];
    if (!inRing(p, big[0])) continue;
    let hole = false;
    for (let k = 1; k < big.length; k++) if (inRing(p, big[k])) hole = true;
    if (hole) continue;
    let d = Infinity;
    for (const r of big) for (let k = 0; k < r.length - 1; k++) d = Math.min(d, segDist(p, r[k], r[k + 1]));
    if (d > bestD) { bestD = d; best = p; }
  }
  return best;
}

let minX = Infinity, minY = Infinity, maxX = -Infinity, maxY = -Infinity;
const provinces = geo.features.map((f) => {
  const polys = ringsOf(f);
  let d = "";
  for (const poly of polys) for (const ring of poly) {
    if (ring.length < 3) continue;
    d += "M" + ring.map(([x, y]) => `${Math.round(x * 10) / 10} ${Math.round((FLIP - y) * 10) / 10}`).join("L") + "Z";
    for (const [x, y] of ring) {
      minX = Math.min(minX, x); maxX = Math.max(maxX, x);
      minY = Math.min(minY, FLIP - y); maxY = Math.max(maxY, FLIP - y);
    }
  }
  const lp = labelPoint(polys);
  const code = CODE[f.properties["hc-key"]];
  return { code, name: NAME_FIX[f.properties.name] ?? f.properties.name, d, label: [Math.round(lp[0]), Math.round(FLIP - lp[1])] };
});
provinces.sort((a, b) => a.name.localeCompare(b.name));

const pad = 60;
const box = { x: Math.floor(minX - pad), y: Math.floor(minY - pad), w: Math.ceil(maxX - minX + pad * 2), h: Math.ceil(maxY - minY + pad * 2) };

const out = `// AUTO-GENERATED by scripts/build-map.mjs — do not edit by hand. Run \`npm run build:map\`.
//
// Offline SVG basemap of South Africa. Province outlines are derived from the Highcharts
// map-collection "za-all" dataset, which is built on public-domain Natural Earth data.
// No tile server, no API key and no network request is needed to render the heritage map.
//
// \`projectLatLng\` maps true WGS84 coordinates into this same SVG space, so every heritage
// pin sits at its real location. Validated against 30 South African towns: each one lands
// inside its correct province (coastal points can sit a few km offshore of the simplified
// 1:10m coastline, which is sub-pixel at display scale).

export const MAP_VIEWBOX = ${JSON.stringify(box)} as const;

export const PROVINCE_NAMES: Record<string, string> = ${JSON.stringify(ABBR, null, 0)};

export type ProvinceShape = { code: string; name: string; d: string; label: [number, number] };

export const PROVINCE_SHAPES: ProvinceShape[] = ${JSON.stringify(provinces, null, 0)};

const AX = ${AX}, BX = ${BX}, AY = ${AY}, BY = ${BY}, FLIP = ${FLIP};

/** True WGS84 lat/lng -> SVG coordinates inside MAP_VIEWBOX. */
export function projectLatLng(lat: number, lng: number): { x: number; y: number } {
  return { x: AX * lng + BX, y: FLIP - (AY * lat + BY) };
}

/** SVG coordinates -> WGS84 lat/lng (inverse of projectLatLng). */
export function unprojectXY(x: number, y: number): { lat: number; lng: number } {
  return { lng: (x - BX) / AX, lat: (FLIP - y - BY) / AY };
}
`;

fs.mkdirSync(path.join(__dirname, "../src/content"), { recursive: true });
fs.writeFileSync(path.join(__dirname, "../src/content/za-map.ts"), out);
console.log("viewBox", box);
console.log("provinces", provinces.map((p) => `${p.code}@${p.label}`).join(" "));
